;LineBlitter core - created by doline.c
lblt_table LABEL WORD
dw OFFSET lblt_0_0
dw OFFSET lblt_0_1
dw OFFSET lblt_0_2
dw OFFSET lblt_0_3
dw OFFSET lblt_0_4
dw OFFSET lblt_0_5
dw OFFSET lblt_0_6
dw OFFSET lblt_0_7
dw OFFSET lblt_0_8
dw OFFSET lblt_0_9
dw OFFSET lblt_0_10
dw OFFSET lblt_0_11
dw OFFSET lblt_0_12
dw OFFSET lblt_0_13
dw OFFSET lblt_0_14
dw OFFSET lblt_0_15
dw OFFSET lblt_1_0
dw OFFSET lblt_1_1
dw OFFSET lblt_1_2
dw OFFSET lblt_1_3
dw OFFSET lblt_1_4
dw OFFSET lblt_1_5
dw OFFSET lblt_1_6
dw OFFSET lblt_1_7
dw OFFSET lblt_1_8
dw OFFSET lblt_1_9
dw OFFSET lblt_1_10
dw OFFSET lblt_1_11
dw OFFSET lblt_1_12
dw OFFSET lblt_1_13
dw OFFSET lblt_1_14
dw OFFSET lblt_1_15
dw OFFSET lblt_2_0
dw OFFSET lblt_2_1
dw OFFSET lblt_2_2
dw OFFSET lblt_2_3
dw OFFSET lblt_2_4
dw OFFSET lblt_2_5
dw OFFSET lblt_2_6
dw OFFSET lblt_2_7
dw OFFSET lblt_2_8
dw OFFSET lblt_2_9
dw OFFSET lblt_2_10
dw OFFSET lblt_2_11
dw OFFSET lblt_2_12
dw OFFSET lblt_2_13
dw OFFSET lblt_2_14
dw OFFSET lblt_2_15
dw OFFSET lblt_3_0
dw OFFSET lblt_3_1
dw OFFSET lblt_3_2
dw OFFSET lblt_3_3
dw OFFSET lblt_3_4
dw OFFSET lblt_3_5
dw OFFSET lblt_3_6
dw OFFSET lblt_3_7
dw OFFSET lblt_3_8
dw OFFSET lblt_3_9
dw OFFSET lblt_3_10
dw OFFSET lblt_3_11
dw OFFSET lblt_3_12
dw OFFSET lblt_3_13
dw OFFSET lblt_3_14
dw OFFSET lblt_3_15
dw OFFSET lblt_4_0
dw OFFSET lblt_4_1
dw OFFSET lblt_4_2
dw OFFSET lblt_4_3
dw OFFSET lblt_4_4
dw OFFSET lblt_4_5
dw OFFSET lblt_4_6
dw OFFSET lblt_4_7
dw OFFSET lblt_4_8
dw OFFSET lblt_4_9
dw OFFSET lblt_4_10
dw OFFSET lblt_4_11
dw OFFSET lblt_4_12
dw OFFSET lblt_4_13
dw OFFSET lblt_4_14
dw OFFSET lblt_4_15
dw OFFSET lblt_5_0
dw OFFSET lblt_5_1
dw OFFSET lblt_5_2
dw OFFSET lblt_5_3
dw OFFSET lblt_5_4
dw OFFSET lblt_5_5
dw OFFSET lblt_5_6
dw OFFSET lblt_5_7
dw OFFSET lblt_5_8
dw OFFSET lblt_5_9
dw OFFSET lblt_5_10
dw OFFSET lblt_5_11
dw OFFSET lblt_5_12
dw OFFSET lblt_5_13
dw OFFSET lblt_5_14
dw OFFSET lblt_5_15
dw OFFSET lblt_6_0
dw OFFSET lblt_6_1
dw OFFSET lblt_6_2
dw OFFSET lblt_6_3
dw OFFSET lblt_6_4
dw OFFSET lblt_6_5
dw OFFSET lblt_6_6
dw OFFSET lblt_6_7
dw OFFSET lblt_6_8
dw OFFSET lblt_6_9
dw OFFSET lblt_6_10
dw OFFSET lblt_6_11
dw OFFSET lblt_6_12
dw OFFSET lblt_6_13
dw OFFSET lblt_6_14
dw OFFSET lblt_6_15
dw OFFSET lblt_7_0
dw OFFSET lblt_7_1
dw OFFSET lblt_7_2
dw OFFSET lblt_7_3
dw OFFSET lblt_7_4
dw OFFSET lblt_7_5
dw OFFSET lblt_7_6
dw OFFSET lblt_7_7
dw OFFSET lblt_7_8
dw OFFSET lblt_7_9
dw OFFSET lblt_7_10
dw OFFSET lblt_7_11
dw OFFSET lblt_7_12
dw OFFSET lblt_7_13
dw OFFSET lblt_7_14
dw OFFSET lblt_7_15
dw OFFSET lblt_8_0
dw OFFSET lblt_8_1
dw OFFSET lblt_8_2
dw OFFSET lblt_8_3
dw OFFSET lblt_8_4
dw OFFSET lblt_8_5
dw OFFSET lblt_8_6
dw OFFSET lblt_8_7
dw OFFSET lblt_8_8
dw OFFSET lblt_8_9
dw OFFSET lblt_8_10
dw OFFSET lblt_8_11
dw OFFSET lblt_8_12
dw OFFSET lblt_8_13
dw OFFSET lblt_8_14
dw OFFSET lblt_8_15
dw OFFSET lblt_9_0
dw OFFSET lblt_9_1
dw OFFSET lblt_9_2
dw OFFSET lblt_9_3
dw OFFSET lblt_9_4
dw OFFSET lblt_9_5
dw OFFSET lblt_9_6
dw OFFSET lblt_9_7
dw OFFSET lblt_9_8
dw OFFSET lblt_9_9
dw OFFSET lblt_9_10
dw OFFSET lblt_9_11
dw OFFSET lblt_9_12
dw OFFSET lblt_9_13
dw OFFSET lblt_9_14
dw OFFSET lblt_9_15
dw OFFSET lblt_10_0
dw OFFSET lblt_10_1
dw OFFSET lblt_10_2
dw OFFSET lblt_10_3
dw OFFSET lblt_10_4
dw OFFSET lblt_10_5
dw OFFSET lblt_10_6
dw OFFSET lblt_10_7
dw OFFSET lblt_10_8
dw OFFSET lblt_10_9
dw OFFSET lblt_10_10
dw OFFSET lblt_10_11
dw OFFSET lblt_10_12
dw OFFSET lblt_10_13
dw OFFSET lblt_10_14
dw OFFSET lblt_10_15
dw OFFSET lblt_11_0
dw OFFSET lblt_11_1
dw OFFSET lblt_11_2
dw OFFSET lblt_11_3
dw OFFSET lblt_11_4
dw OFFSET lblt_11_5
dw OFFSET lblt_11_6
dw OFFSET lblt_11_7
dw OFFSET lblt_11_8
dw OFFSET lblt_11_9
dw OFFSET lblt_11_10
dw OFFSET lblt_11_11
dw OFFSET lblt_11_12
dw OFFSET lblt_11_13
dw OFFSET lblt_11_14
dw OFFSET lblt_11_15
dw OFFSET lblt_12_0
dw OFFSET lblt_12_1
dw OFFSET lblt_12_2
dw OFFSET lblt_12_3
dw OFFSET lblt_12_4
dw OFFSET lblt_12_5
dw OFFSET lblt_12_6
dw OFFSET lblt_12_7
dw OFFSET lblt_12_8
dw OFFSET lblt_12_9
dw OFFSET lblt_12_10
dw OFFSET lblt_12_11
dw OFFSET lblt_12_12
dw OFFSET lblt_12_13
dw OFFSET lblt_12_14
dw OFFSET lblt_12_15
dw OFFSET lblt_13_0
dw OFFSET lblt_13_1
dw OFFSET lblt_13_2
dw OFFSET lblt_13_3
dw OFFSET lblt_13_4
dw OFFSET lblt_13_5
dw OFFSET lblt_13_6
dw OFFSET lblt_13_7
dw OFFSET lblt_13_8
dw OFFSET lblt_13_9
dw OFFSET lblt_13_10
dw OFFSET lblt_13_11
dw OFFSET lblt_13_12
dw OFFSET lblt_13_13
dw OFFSET lblt_13_14
dw OFFSET lblt_13_15
dw OFFSET lblt_14_0
dw OFFSET lblt_14_1
dw OFFSET lblt_14_2
dw OFFSET lblt_14_3
dw OFFSET lblt_14_4
dw OFFSET lblt_14_5
dw OFFSET lblt_14_6
dw OFFSET lblt_14_7
dw OFFSET lblt_14_8
dw OFFSET lblt_14_9
dw OFFSET lblt_14_10
dw OFFSET lblt_14_11
dw OFFSET lblt_14_12
dw OFFSET lblt_14_13
dw OFFSET lblt_14_14
dw OFFSET lblt_14_15
dw OFFSET lblt_15_0
dw OFFSET lblt_15_1
dw OFFSET lblt_15_2
dw OFFSET lblt_15_3
dw OFFSET lblt_15_4
dw OFFSET lblt_15_5
dw OFFSET lblt_15_6
dw OFFSET lblt_15_7
dw OFFSET lblt_15_8
dw OFFSET lblt_15_9
dw OFFSET lblt_15_10
dw OFFSET lblt_15_11
dw OFFSET lblt_15_12
dw OFFSET lblt_15_13
dw OFFSET lblt_15_14
dw OFFSET lblt_15_15
lblt_0_0:
ret
lblt_0_1:
mov es:[di+0],al
ret
lblt_0_2:
mov es:[di+0],al
mov es:[di+320],al
ret
lblt_0_3:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
ret
lblt_0_4:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
ret
lblt_0_5:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
ret
lblt_0_6:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
ret
lblt_0_7:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
ret
lblt_0_8:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2240],al
ret
lblt_0_9:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2240],al
mov es:[di+2560],al
ret
lblt_0_10:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2240],al
mov es:[di+2560],al
mov es:[di+2880],al
ret
lblt_0_11:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2240],al
mov es:[di+2560],al
mov es:[di+2880],al
mov es:[di+3200],al
ret
lblt_0_12:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2240],al
mov es:[di+2560],al
mov es:[di+2880],al
mov es:[di+3200],al
mov es:[di+3520],al
ret
lblt_0_13:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2240],al
mov es:[di+2560],al
mov es:[di+2880],al
mov es:[di+3200],al
mov es:[di+3520],al
mov es:[di+3840],al
ret
lblt_0_14:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2240],al
mov es:[di+2560],al
mov es:[di+2880],al
mov es:[di+3200],al
mov es:[di+3520],al
mov es:[di+3840],al
mov es:[di+4160],al
ret
lblt_0_15:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2240],al
mov es:[di+2560],al
mov es:[di+2880],al
mov es:[di+3200],al
mov es:[di+3520],al
mov es:[di+3840],al
mov es:[di+4160],al
mov es:[di+4480],al
ret
lblt_1_0:
mov es:[di+0],al
ret
lblt_1_1:
mov es:[di+0],al
ret
lblt_1_2:
mov es:[di+0],al
mov es:[di+320],al
ret
lblt_1_3:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
ret
lblt_1_4:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+961],al
ret
lblt_1_5:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+961],al
mov es:[di+1281],al
ret
lblt_1_6:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1281],al
mov es:[di+1601],al
ret
lblt_1_7:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
ret
lblt_1_8:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2241],al
ret
lblt_1_9:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2561],al
ret
lblt_1_10:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2561],al
mov es:[di+2881],al
ret
lblt_1_11:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2561],al
mov es:[di+2881],al
mov es:[di+3201],al
ret
lblt_1_12:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2241],al
mov es:[di+2561],al
mov es:[di+2881],al
mov es:[di+3201],al
mov es:[di+3521],al
ret
lblt_1_13:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2241],al
mov es:[di+2561],al
mov es:[di+2881],al
mov es:[di+3201],al
mov es:[di+3521],al
mov es:[di+3841],al
ret
lblt_1_14:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2240],al
mov es:[di+2561],al
mov es:[di+2881],al
mov es:[di+3201],al
mov es:[di+3521],al
mov es:[di+3841],al
mov es:[di+4161],al
ret
lblt_1_15:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1280],al
mov es:[di+1600],al
mov es:[di+1920],al
mov es:[di+2240],al
mov es:[di+2561],al
mov es:[di+2881],al
mov es:[di+3201],al
mov es:[di+3521],al
mov es:[di+3841],al
mov es:[di+4161],al
mov es:[di+4481],al
ret
lblt_2_0:
mov es:[di+0],ax
ret
lblt_2_1:
mov es:[di+0],ax
ret
lblt_2_2:
mov es:[di+0],al
mov es:[di+321],al
ret
lblt_2_3:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
ret
lblt_2_4:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
ret
lblt_2_5:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
ret
lblt_2_6:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1602],al
ret
lblt_2_7:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1922],al
ret
lblt_2_8:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2242],al
ret
lblt_2_9:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2242],al
mov es:[di+2562],al
ret
lblt_2_10:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2562],al
mov es:[di+2882],al
ret
lblt_2_11:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2561],al
mov es:[di+2882],al
mov es:[di+3202],al
ret
lblt_2_12:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2561],al
mov es:[di+2881],al
mov es:[di+3202],al
mov es:[di+3522],al
ret
lblt_2_13:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2561],al
mov es:[di+2881],al
mov es:[di+3202],al
mov es:[di+3522],al
mov es:[di+3842],al
ret
lblt_2_14:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2561],al
mov es:[di+2881],al
mov es:[di+3201],al
mov es:[di+3522],al
mov es:[di+3842],al
mov es:[di+4162],al
ret
lblt_2_15:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+960],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2561],al
mov es:[di+2881],al
mov es:[di+3201],al
mov es:[di+3521],al
mov es:[di+3842],al
mov es:[di+4162],al
mov es:[di+4482],al
ret
lblt_3_0:
mov es:[di+0],ax
mov es:[di+2],al
ret
lblt_3_1:
mov es:[di+0],ax
mov es:[di+322],al
ret
lblt_3_2:
mov es:[di+0],al
mov es:[di+321],ax
ret
lblt_3_3:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
ret
lblt_3_4:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
ret
lblt_3_5:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
ret
lblt_3_6:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
ret
lblt_3_7:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1923],al
ret
lblt_3_8:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2243],al
ret
lblt_3_9:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2242],al
mov es:[di+2563],al
ret
lblt_3_10:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1922],al
mov es:[di+2242],al
mov es:[di+2562],al
mov es:[di+2883],al
ret
lblt_3_11:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1922],al
mov es:[di+2242],al
mov es:[di+2562],al
mov es:[di+2882],al
mov es:[di+3203],al
ret
lblt_3_12:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2242],al
mov es:[di+2562],al
mov es:[di+2882],al
mov es:[di+3202],al
mov es:[di+3523],al
ret
lblt_3_13:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2242],al
mov es:[di+2562],al
mov es:[di+2882],al
mov es:[di+3202],al
mov es:[di+3523],al
mov es:[di+3843],al
ret
lblt_3_14:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2562],al
mov es:[di+2882],al
mov es:[di+3202],al
mov es:[di+3522],al
mov es:[di+3843],al
mov es:[di+4163],al
ret
lblt_3_15:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+640],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1921],al
mov es:[di+2241],al
mov es:[di+2562],al
mov es:[di+2882],al
mov es:[di+3202],al
mov es:[di+3522],al
mov es:[di+3842],al
mov es:[di+4163],al
mov es:[di+4483],al
ret
lblt_4_0:
mov es:[di+0],ax
mov es:[di+2],ax
ret
lblt_4_1:
mov es:[di+0],ax
mov es:[di+2],al
mov es:[di+323],al
ret
lblt_4_2:
mov es:[di+0],ax
mov es:[di+322],ax
ret
lblt_4_3:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
ret
lblt_4_4:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
ret
lblt_4_5:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+962],al
mov es:[di+1283],al
ret
lblt_4_6:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1603],al
ret
lblt_4_7:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1923],al
ret
lblt_4_8:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1923],al
mov es:[di+2243],al
ret
lblt_4_9:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1923],al
mov es:[di+2243],al
mov es:[di+2564],al
ret
lblt_4_10:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2243],al
mov es:[di+2563],al
mov es:[di+2884],al
ret
lblt_4_11:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2243],al
mov es:[di+2563],al
mov es:[di+2883],al
mov es:[di+3204],al
ret
lblt_4_12:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2242],al
mov es:[di+2563],al
mov es:[di+2883],al
mov es:[di+3203],al
mov es:[di+3524],al
ret
lblt_4_13:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2242],al
mov es:[di+2562],al
mov es:[di+2883],al
mov es:[di+3203],al
mov es:[di+3523],al
mov es:[di+3844],al
ret
lblt_4_14:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1922],al
mov es:[di+2242],al
mov es:[di+2562],al
mov es:[di+2883],al
mov es:[di+3203],al
mov es:[di+3523],al
mov es:[di+3843],al
mov es:[di+4164],al
ret
lblt_4_15:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1601],al
mov es:[di+1922],al
mov es:[di+2242],al
mov es:[di+2562],al
mov es:[di+2882],al
mov es:[di+3203],al
mov es:[di+3523],al
mov es:[di+3843],al
mov es:[di+4163],al
mov es:[di+4484],al
ret
lblt_5_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],al
ret
lblt_5_1:
mov es:[di+0],ax
mov es:[di+2],al
mov es:[di+323],ax
ret
lblt_5_2:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],al
ret
lblt_5_3:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
ret
lblt_5_4:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],ax
mov es:[di+964],al
ret
lblt_5_5:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
ret
lblt_5_6:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
ret
lblt_5_7:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1924],al
ret
lblt_5_8:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2244],al
ret
lblt_5_9:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1923],al
mov es:[di+2244],al
mov es:[di+2564],al
ret
lblt_5_10:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1923],al
mov es:[di+2243],al
mov es:[di+2564],al
mov es:[di+2884],al
ret
lblt_5_11:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1923],al
mov es:[di+2243],al
mov es:[di+2564],al
mov es:[di+2884],al
mov es:[di+3205],al
ret
lblt_5_12:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2243],al
mov es:[di+2563],al
mov es:[di+2884],al
mov es:[di+3204],al
mov es:[di+3525],al
ret
lblt_5_13:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2243],al
mov es:[di+2563],al
mov es:[di+2883],al
mov es:[di+3204],al
mov es:[di+3524],al
mov es:[di+3845],al
ret
lblt_5_14:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2242],al
mov es:[di+2563],al
mov es:[di+2883],al
mov es:[di+3204],al
mov es:[di+3524],al
mov es:[di+3844],al
mov es:[di+4165],al
ret
lblt_5_15:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1281],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2242],al
mov es:[di+2563],al
mov es:[di+2883],al
mov es:[di+3203],al
mov es:[di+3524],al
mov es:[di+3844],al
mov es:[di+4164],al
mov es:[di+4485],al
ret
lblt_6_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
ret
lblt_6_1:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+324],ax
ret
lblt_6_2:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],al
mov es:[di+645],al
ret
lblt_6_3:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
ret
lblt_6_4:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],ax
ret
lblt_6_5:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],ax
mov es:[di+964],al
mov es:[di+1285],al
ret
lblt_6_6:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
ret
lblt_6_7:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
ret
lblt_6_8:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1924],al
mov es:[di+2245],al
ret
lblt_6_9:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2245],al
mov es:[di+2565],al
ret
lblt_6_10:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2244],al
mov es:[di+2565],al
mov es:[di+2885],al
ret
lblt_6_11:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1923],al
mov es:[di+2244],al
mov es:[di+2564],al
mov es:[di+2885],al
mov es:[di+3205],al
ret
lblt_6_12:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1923],al
mov es:[di+2243],al
mov es:[di+2564],al
mov es:[di+2884],al
mov es:[di+3205],al
mov es:[di+3525],al
ret
lblt_6_13:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1923],al
mov es:[di+2243],al
mov es:[di+2564],al
mov es:[di+2884],al
mov es:[di+3205],al
mov es:[di+3525],al
mov es:[di+3846],al
ret
lblt_6_14:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1923],al
mov es:[di+2243],al
mov es:[di+2563],al
mov es:[di+2884],al
mov es:[di+3204],al
mov es:[di+3525],al
mov es:[di+3845],al
mov es:[di+4166],al
ret
lblt_6_15:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1922],al
mov es:[di+2243],al
mov es:[di+2563],al
mov es:[di+2884],al
mov es:[di+3204],al
mov es:[di+3524],al
mov es:[di+3845],al
mov es:[di+4165],al
mov es:[di+4486],al
ret
lblt_7_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],al
ret
lblt_7_1:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+324],ax
mov es:[di+326],al
ret
lblt_7_2:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],ax
mov es:[di+646],al
ret
lblt_7_3:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+966],al
ret
lblt_7_4:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],ax
ret
lblt_7_5:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],al
mov es:[di+1285],ax
ret
lblt_7_6:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],ax
mov es:[di+1285],al
mov es:[di+1606],al
ret
lblt_7_7:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
ret
lblt_7_8:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2246],al
ret
lblt_7_9:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2245],al
mov es:[di+2566],al
ret
lblt_7_10:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2245],al
mov es:[di+2566],al
mov es:[di+2886],al
ret
lblt_7_11:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2244],al
mov es:[di+2565],al
mov es:[di+2886],al
mov es:[di+3206],al
ret
lblt_7_12:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1923],al
mov es:[di+2244],al
mov es:[di+2565],al
mov es:[di+2885],al
mov es:[di+3206],al
mov es:[di+3526],al
ret
lblt_7_13:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1923],al
mov es:[di+2244],al
mov es:[di+2564],al
mov es:[di+2885],al
mov es:[di+3205],al
mov es:[di+3526],al
mov es:[di+3846],al
ret
lblt_7_14:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1923],al
mov es:[di+2243],al
mov es:[di+2564],al
mov es:[di+2884],al
mov es:[di+3205],al
mov es:[di+3525],al
mov es:[di+3846],al
mov es:[di+4166],al
ret
lblt_7_15:
mov es:[di+0],al
mov es:[di+320],al
mov es:[di+641],al
mov es:[di+961],al
mov es:[di+1282],al
mov es:[di+1602],al
mov es:[di+1923],al
mov es:[di+2243],al
mov es:[di+2564],al
mov es:[di+2884],al
mov es:[di+3205],al
mov es:[di+3525],al
mov es:[di+3846],al
mov es:[di+4166],al
mov es:[di+4487],al
ret
lblt_8_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],ax
ret
lblt_8_1:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],al
mov es:[di+325],ax
mov es:[di+327],al
ret
lblt_8_2:
mov es:[di+0],ax
mov es:[di+2],al
mov es:[di+323],ax
mov es:[di+325],ax
mov es:[di+647],al
ret
lblt_8_3:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],al
mov es:[di+645],ax
mov es:[di+967],al
ret
lblt_8_4:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+966],ax
ret
lblt_8_5:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],al
mov es:[di+1286],ax
ret
lblt_8_6:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],al
mov es:[di+1285],ax
mov es:[di+1607],al
ret
lblt_8_7:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],ax
mov es:[di+1285],al
mov es:[di+1606],al
mov es:[di+1927],al
ret
lblt_8_8:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2247],al
ret
lblt_8_9:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2567],al
ret
lblt_8_10:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2566],al
mov es:[di+2887],al
ret
lblt_8_11:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1924],al
mov es:[di+2245],al
mov es:[di+2566],al
mov es:[di+2887],al
mov es:[di+3207],al
ret
lblt_8_12:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2245],al
mov es:[di+2565],al
mov es:[di+2886],al
mov es:[di+3207],al
mov es:[di+3527],al
ret
lblt_8_13:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2244],al
mov es:[di+2565],al
mov es:[di+2886],al
mov es:[di+3206],al
mov es:[di+3527],al
mov es:[di+3847],al
ret
lblt_8_14:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1923],al
mov es:[di+2244],al
mov es:[di+2565],al
mov es:[di+2885],al
mov es:[di+3206],al
mov es:[di+3526],al
mov es:[di+3847],al
mov es:[di+4167],al
ret
lblt_8_15:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1923],al
mov es:[di+2244],al
mov es:[di+2564],al
mov es:[di+2885],al
mov es:[di+3205],al
mov es:[di+3526],al
mov es:[di+3846],al
mov es:[di+4167],al
mov es:[di+4487],al
ret
lblt_9_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],ax
mov es:[di+8],al
ret
lblt_9_1:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],al
mov es:[di+325],ax
mov es:[di+327],ax
ret
lblt_9_2:
mov es:[di+0],ax
mov es:[di+2],al
mov es:[di+323],ax
mov es:[di+325],ax
mov es:[di+647],ax
ret
lblt_9_3:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],al
mov es:[di+645],ax
mov es:[di+647],al
mov es:[di+968],al
ret
lblt_9_4:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+966],ax
mov es:[di+1288],al
ret
lblt_9_5:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],ax
mov es:[di+1287],ax
ret
lblt_9_6:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],ax
mov es:[di+1286],al
mov es:[di+1607],ax
ret
lblt_9_7:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],ax
mov es:[di+964],al
mov es:[di+1285],al
mov es:[di+1606],ax
mov es:[di+1928],al
ret
lblt_9_8:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],ax
mov es:[di+1606],al
mov es:[di+1927],al
mov es:[di+2248],al
ret
lblt_9_9:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2247],al
mov es:[di+2568],al
ret
lblt_9_10:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2567],al
mov es:[di+2888],al
ret
lblt_9_11:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2567],al
mov es:[di+2887],al
mov es:[di+3208],al
ret
lblt_9_12:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1924],al
mov es:[di+2245],al
mov es:[di+2566],al
mov es:[di+2887],al
mov es:[di+3207],al
mov es:[di+3528],al
ret
lblt_9_13:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2245],al
mov es:[di+2566],al
mov es:[di+2886],al
mov es:[di+3207],al
mov es:[di+3528],al
mov es:[di+3848],al
ret
lblt_9_14:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2244],al
mov es:[di+2565],al
mov es:[di+2886],al
mov es:[di+3206],al
mov es:[di+3527],al
mov es:[di+3848],al
mov es:[di+4168],al
ret
lblt_9_15:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1282],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2244],al
mov es:[di+2565],al
mov es:[di+2885],al
mov es:[di+3206],al
mov es:[di+3527],al
mov es:[di+3847],al
mov es:[di+4168],al
mov es:[di+4488],al
ret
lblt_10_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],ax
mov es:[di+8],ax
ret
lblt_10_1:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+326],ax
mov es:[di+328],ax
ret
lblt_10_2:
mov es:[di+0],ax
mov es:[di+2],al
mov es:[di+323],ax
mov es:[di+325],ax
mov es:[di+327],al
mov es:[di+648],ax
ret
lblt_10_3:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],ax
mov es:[di+646],ax
mov es:[di+648],al
mov es:[di+969],al
ret
lblt_10_4:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+646],al
mov es:[di+967],ax
mov es:[di+1289],al
ret
lblt_10_5:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+966],ax
mov es:[di+1288],ax
ret
lblt_10_6:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],al
mov es:[di+1286],ax
mov es:[di+1608],ax
ret
lblt_10_7:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],ax
mov es:[di+1286],al
mov es:[di+1607],al
mov es:[di+1928],ax
ret
lblt_10_8:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],ax
mov es:[di+964],al
mov es:[di+1285],al
mov es:[di+1606],al
mov es:[di+1927],ax
mov es:[di+2249],al
ret
lblt_10_9:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],ax
mov es:[di+1606],al
mov es:[di+1927],al
mov es:[di+2248],al
mov es:[di+2569],al
ret
lblt_10_10:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2247],al
mov es:[di+2568],al
mov es:[di+2889],al
ret
lblt_10_11:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2567],al
mov es:[di+2888],al
mov es:[di+3209],al
ret
lblt_10_12:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2567],al
mov es:[di+2887],al
mov es:[di+3208],al
mov es:[di+3529],al
ret
lblt_10_13:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2245],al
mov es:[di+2566],al
mov es:[di+2887],al
mov es:[di+3208],al
mov es:[di+3528],al
mov es:[di+3849],al
ret
lblt_10_14:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1924],al
mov es:[di+2245],al
mov es:[di+2566],al
mov es:[di+2886],al
mov es:[di+3207],al
mov es:[di+3528],al
mov es:[di+3849],al
mov es:[di+4169],al
ret
lblt_10_15:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1603],al
mov es:[di+1924],al
mov es:[di+2245],al
mov es:[di+2565],al
mov es:[di+2886],al
mov es:[di+3207],al
mov es:[di+3527],al
mov es:[di+3848],al
mov es:[di+4169],al
mov es:[di+4489],al
ret
lblt_11_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],ax
mov es:[di+8],ax
mov es:[di+10],al
ret
lblt_11_1:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+326],ax
mov es:[di+328],ax
mov es:[di+330],al
ret
lblt_11_2:
mov es:[di+0],ax
mov es:[di+2],al
mov es:[di+323],ax
mov es:[di+325],ax
mov es:[di+327],ax
mov es:[di+649],ax
ret
lblt_11_3:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],ax
mov es:[di+646],ax
mov es:[di+648],ax
mov es:[di+970],al
ret
lblt_11_4:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],al
mov es:[di+645],ax
mov es:[di+967],ax
mov es:[di+969],al
mov es:[di+1290],al
ret
lblt_11_5:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+966],ax
mov es:[di+1288],ax
mov es:[di+1610],al
ret
lblt_11_6:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],ax
mov es:[di+1287],ax
mov es:[di+1609],ax
ret
lblt_11_7:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],ax
mov es:[di+1286],ax
mov es:[di+1608],al
mov es:[di+1929],ax
ret
lblt_11_8:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],al
mov es:[di+1285],ax
mov es:[di+1607],al
mov es:[di+1928],al
mov es:[di+2249],ax
ret
lblt_11_9:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],ax
mov es:[di+964],al
mov es:[di+1285],al
mov es:[di+1606],al
mov es:[di+1927],al
mov es:[di+2248],ax
mov es:[di+2570],al
ret
lblt_11_10:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],ax
mov es:[di+1927],al
mov es:[di+2248],al
mov es:[di+2569],al
mov es:[di+2890],al
ret
lblt_11_11:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2247],al
mov es:[di+2568],al
mov es:[di+2889],al
mov es:[di+3210],al
ret
lblt_11_12:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2567],al
mov es:[di+2888],al
mov es:[di+3209],al
mov es:[di+3530],al
ret
lblt_11_13:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2567],al
mov es:[di+2888],al
mov es:[di+3208],al
mov es:[di+3529],al
mov es:[di+3850],al
ret
lblt_11_14:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2245],al
mov es:[di+2566],al
mov es:[di+2887],al
mov es:[di+3208],al
mov es:[di+3529],al
mov es:[di+3849],al
mov es:[di+4170],al
ret
lblt_11_15:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+641],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1924],al
mov es:[di+2245],al
mov es:[di+2566],al
mov es:[di+2887],al
mov es:[di+3207],al
mov es:[di+3528],al
mov es:[di+3849],al
mov es:[di+4170],al
mov es:[di+4490],al
ret
lblt_12_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],ax
mov es:[di+8],ax
mov es:[di+10],ax
ret
lblt_12_1:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],al
mov es:[di+327],ax
mov es:[di+329],ax
mov es:[di+331],al
ret
lblt_12_2:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+324],ax
mov es:[di+326],ax
mov es:[di+328],ax
mov es:[di+650],ax
ret
lblt_12_3:
mov es:[di+0],ax
mov es:[di+2],al
mov es:[di+323],ax
mov es:[di+325],ax
mov es:[di+647],ax
mov es:[di+649],ax
mov es:[di+971],al
ret
lblt_12_4:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],al
mov es:[di+645],ax
mov es:[di+647],al
mov es:[di+968],ax
mov es:[di+970],al
mov es:[di+1291],al
ret
lblt_12_5:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+646],al
mov es:[di+967],ax
mov es:[di+1289],ax
mov es:[di+1611],al
ret
lblt_12_6:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+966],ax
mov es:[di+1288],ax
mov es:[di+1610],ax
ret
lblt_12_7:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],ax
mov es:[di+1287],al
mov es:[di+1608],ax
mov es:[di+1930],ax
ret
lblt_12_8:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],ax
mov es:[di+1286],al
mov es:[di+1607],ax
mov es:[di+1929],al
mov es:[di+2250],ax
ret
lblt_12_9:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],al
mov es:[di+1285],ax
mov es:[di+1607],al
mov es:[di+1928],al
mov es:[di+2249],ax
mov es:[di+2571],al
ret
lblt_12_10:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],ax
mov es:[di+964],al
mov es:[di+1285],al
mov es:[di+1606],al
mov es:[di+1927],al
mov es:[di+2248],ax
mov es:[di+2570],al
mov es:[di+2891],al
ret
lblt_12_11:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],ax
mov es:[di+1927],al
mov es:[di+2248],al
mov es:[di+2569],al
mov es:[di+2890],al
mov es:[di+3211],al
ret
lblt_12_12:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2247],al
mov es:[di+2568],al
mov es:[di+2889],al
mov es:[di+3210],al
mov es:[di+3531],al
ret
lblt_12_13:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2246],al
mov es:[di+2567],al
mov es:[di+2888],al
mov es:[di+3209],al
mov es:[di+3530],al
mov es:[di+3851],al
ret
lblt_12_14:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2567],al
mov es:[di+2888],al
mov es:[di+3209],al
mov es:[di+3529],al
mov es:[di+3850],al
mov es:[di+4171],al
ret
lblt_12_15:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+962],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2566],al
mov es:[di+2887],al
mov es:[di+3208],al
mov es:[di+3529],al
mov es:[di+3850],al
mov es:[di+4170],al
mov es:[di+4491],al
ret
lblt_13_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],ax
mov es:[di+8],ax
mov es:[di+10],ax
mov es:[di+12],al
ret
lblt_13_1:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],al
mov es:[di+327],ax
mov es:[di+329],ax
mov es:[di+331],ax
ret
lblt_13_2:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+324],ax
mov es:[di+326],ax
mov es:[di+328],ax
mov es:[di+650],ax
mov es:[di+652],al
ret
lblt_13_3:
mov es:[di+0],ax
mov es:[di+2],al
mov es:[di+323],ax
mov es:[di+325],ax
mov es:[di+647],ax
mov es:[di+649],ax
mov es:[di+971],ax
ret
lblt_13_4:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],al
mov es:[di+645],ax
mov es:[di+647],ax
mov es:[di+969],ax
mov es:[di+971],al
mov es:[di+1292],al
ret
lblt_13_5:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+646],al
mov es:[di+967],ax
mov es:[di+969],al
mov es:[di+1290],ax
mov es:[di+1612],al
ret
lblt_13_6:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+966],ax
mov es:[di+1288],ax
mov es:[di+1610],ax
mov es:[di+1932],al
ret
lblt_13_7:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],ax
mov es:[di+1287],ax
mov es:[di+1609],ax
mov es:[di+1931],ax
ret
lblt_13_8:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],al
mov es:[di+1286],ax
mov es:[di+1608],al
mov es:[di+1929],ax
mov es:[di+2251],ax
ret
lblt_13_9:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],ax
mov es:[di+1286],al
mov es:[di+1607],al
mov es:[di+1928],ax
mov es:[di+2250],al
mov es:[di+2571],ax
ret
lblt_13_10:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],ax
mov es:[di+964],al
mov es:[di+1285],al
mov es:[di+1606],ax
mov es:[di+1928],al
mov es:[di+2249],al
mov es:[di+2570],ax
mov es:[di+2892],al
ret
lblt_13_11:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],ax
mov es:[di+1285],al
mov es:[di+1606],al
mov es:[di+1927],al
mov es:[di+2248],al
mov es:[di+2569],ax
mov es:[di+2891],al
mov es:[di+3212],al
ret
lblt_13_12:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],ax
mov es:[di+2248],al
mov es:[di+2569],al
mov es:[di+2890],al
mov es:[di+3211],al
mov es:[di+3532],al
ret
lblt_13_13:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2247],al
mov es:[di+2568],al
mov es:[di+2889],al
mov es:[di+3210],al
mov es:[di+3531],al
mov es:[di+3852],al
ret
lblt_13_14:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2246],al
mov es:[di+2567],al
mov es:[di+2888],al
mov es:[di+3209],al
mov es:[di+3530],al
mov es:[di+3851],al
mov es:[di+4172],al
ret
lblt_13_15:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1283],al
mov es:[di+1604],al
mov es:[di+1925],al
mov es:[di+2246],al
mov es:[di+2567],al
mov es:[di+2888],al
mov es:[di+3209],al
mov es:[di+3530],al
mov es:[di+3850],al
mov es:[di+4171],al
mov es:[di+4492],al
ret
lblt_14_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],ax
mov es:[di+8],ax
mov es:[di+10],ax
mov es:[di+12],ax
ret
lblt_14_1:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],ax
mov es:[di+328],ax
mov es:[di+330],ax
mov es:[di+332],ax
ret
lblt_14_2:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+324],ax
mov es:[di+326],ax
mov es:[di+328],ax
mov es:[di+330],al
mov es:[di+651],ax
mov es:[di+653],al
ret
lblt_14_3:
mov es:[di+0],ax
mov es:[di+2],al
mov es:[di+323],ax
mov es:[di+325],ax
mov es:[di+327],al
mov es:[di+648],ax
mov es:[di+650],ax
mov es:[di+972],ax
ret
lblt_14_4:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],ax
mov es:[di+646],ax
mov es:[di+648],al
mov es:[di+969],ax
mov es:[di+971],ax
mov es:[di+1293],al
ret
lblt_14_5:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],al
mov es:[di+645],ax
mov es:[di+647],al
mov es:[di+968],ax
mov es:[di+1290],ax
mov es:[di+1292],al
mov es:[di+1613],al
ret
lblt_14_6:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+966],ax
mov es:[di+968],al
mov es:[di+1289],ax
mov es:[di+1611],ax
mov es:[di+1933],al
ret
lblt_14_7:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+966],ax
mov es:[di+1288],ax
mov es:[di+1610],ax
mov es:[di+1932],ax
ret
lblt_14_8:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],ax
mov es:[di+1287],al
mov es:[di+1608],ax
mov es:[di+1930],ax
mov es:[di+2252],ax
ret
lblt_14_9:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],ax
mov es:[di+1286],ax
mov es:[di+1608],al
mov es:[di+1929],ax
mov es:[di+2251],al
mov es:[di+2572],ax
ret
lblt_14_10:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],al
mov es:[di+1285],ax
mov es:[di+1607],al
mov es:[di+1928],ax
mov es:[di+2250],al
mov es:[di+2571],al
mov es:[di+2892],ax
ret
lblt_14_11:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],ax
mov es:[di+964],al
mov es:[di+1285],al
mov es:[di+1606],ax
mov es:[di+1928],al
mov es:[di+2249],al
mov es:[di+2570],al
mov es:[di+2891],ax
mov es:[di+3213],al
ret
lblt_14_12:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],ax
mov es:[di+1285],al
mov es:[di+1606],al
mov es:[di+1927],al
mov es:[di+2248],al
mov es:[di+2569],al
mov es:[di+2890],ax
mov es:[di+3212],al
mov es:[di+3533],al
ret
lblt_14_13:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],ax
mov es:[di+2248],al
mov es:[di+2569],al
mov es:[di+2890],al
mov es:[di+3211],al
mov es:[di+3532],al
mov es:[di+3853],al
ret
lblt_14_14:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2247],al
mov es:[di+2568],al
mov es:[di+2889],al
mov es:[di+3210],al
mov es:[di+3531],al
mov es:[di+3852],al
mov es:[di+4173],al
ret
lblt_14_15:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2247],al
mov es:[di+2567],al
mov es:[di+2888],al
mov es:[di+3209],al
mov es:[di+3530],al
mov es:[di+3851],al
mov es:[di+4172],al
mov es:[di+4493],al
ret
lblt_15_0:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],ax
mov es:[di+8],ax
mov es:[di+10],ax
mov es:[di+12],ax
mov es:[di+14],al
ret
lblt_15_1:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+4],ax
mov es:[di+6],ax
mov es:[di+328],ax
mov es:[di+330],ax
mov es:[di+332],ax
mov es:[di+334],al
ret
lblt_15_2:
mov es:[di+0],ax
mov es:[di+2],ax
mov es:[di+324],ax
mov es:[di+326],ax
mov es:[di+328],ax
mov es:[di+330],ax
mov es:[di+652],ax
mov es:[di+654],al
ret
lblt_15_3:
mov es:[di+0],ax
mov es:[di+2],al
mov es:[di+323],ax
mov es:[di+325],ax
mov es:[di+327],al
mov es:[di+648],ax
mov es:[di+650],ax
mov es:[di+652],al
mov es:[di+973],ax
ret
lblt_15_4:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],ax
mov es:[di+646],ax
mov es:[di+648],ax
mov es:[di+970],ax
mov es:[di+972],ax
mov es:[di+1294],al
ret
lblt_15_5:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+324],al
mov es:[di+645],ax
mov es:[di+647],al
mov es:[di+968],ax
mov es:[di+970],al
mov es:[di+1291],ax
mov es:[di+1293],al
mov es:[di+1614],al
ret
lblt_15_6:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+646],al
mov es:[di+967],ax
mov es:[di+1289],ax
mov es:[di+1291],al
mov es:[di+1612],ax
mov es:[di+1934],al
ret
lblt_15_7:
mov es:[di+0],ax
mov es:[di+322],ax
mov es:[di+644],ax
mov es:[di+966],ax
mov es:[di+1288],ax
mov es:[di+1610],ax
mov es:[di+1932],ax
mov es:[di+2254],al
ret
lblt_15_8:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],ax
mov es:[di+1287],ax
mov es:[di+1609],ax
mov es:[di+1931],ax
mov es:[di+2253],ax
ret
lblt_15_9:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],ax
mov es:[di+965],al
mov es:[di+1286],ax
mov es:[di+1608],ax
mov es:[di+1930],al
mov es:[di+2251],ax
mov es:[di+2573],ax
ret
lblt_15_10:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],ax
mov es:[di+1286],al
mov es:[di+1607],ax
mov es:[di+1929],al
mov es:[di+2250],ax
mov es:[di+2572],al
mov es:[di+2893],ax
ret
lblt_15_11:
mov es:[di+0],al
mov es:[di+321],ax
mov es:[di+643],al
mov es:[di+964],al
mov es:[di+1285],ax
mov es:[di+1607],al
mov es:[di+1928],al
mov es:[di+2249],ax
mov es:[di+2571],al
mov es:[di+2892],al
mov es:[di+3213],ax
ret
lblt_15_12:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],ax
mov es:[di+964],al
mov es:[di+1285],al
mov es:[di+1606],al
mov es:[di+1927],ax
mov es:[di+2249],al
mov es:[di+2570],al
mov es:[di+2891],al
mov es:[di+3212],ax
mov es:[di+3534],al
ret
lblt_15_13:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],ax
mov es:[di+1285],al
mov es:[di+1606],al
mov es:[di+1927],al
mov es:[di+2248],al
mov es:[di+2569],al
mov es:[di+2890],al
mov es:[di+3211],ax
mov es:[di+3533],al
mov es:[di+3854],al
ret
lblt_15_14:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2247],ax
mov es:[di+2569],al
mov es:[di+2890],al
mov es:[di+3211],al
mov es:[di+3532],al
mov es:[di+3853],al
mov es:[di+4174],al
ret
lblt_15_15:
mov es:[di+0],al
mov es:[di+321],al
mov es:[di+642],al
mov es:[di+963],al
mov es:[di+1284],al
mov es:[di+1605],al
mov es:[di+1926],al
mov es:[di+2247],al
mov es:[di+2568],al
mov es:[di+2889],al
mov es:[di+3210],al
mov es:[di+3531],al
mov es:[di+3852],al
mov es:[di+4173],al
mov es:[di+4494],al
ret
