;LineBlitter core - created by doline.c
dw OFFSET lblt_1b0 ;only dot
lblt_table LABEL WORD
dw OFFSET lblt_54b56
dw OFFSET lblt_55b56
dw OFFSET lblt_56b56
dw OFFSET lblt_57b56
dw OFFSET lblt_58b56
dw OFFSET lblt_59b56
dw OFFSET lblt_60b56
dw OFFSET lblt_61b56
dw OFFSET lblt_62b56
dw OFFSET lblt_63b56
dw OFFSET lblt_0b56
dw OFFSET lblt_1b56
dw OFFSET lblt_2b56
dw OFFSET lblt_3b56
dw OFFSET lblt_4b56
dw OFFSET lblt_5b56
dw OFFSET lblt_6b56
dw OFFSET lblt_7b56
dw OFFSET lblt_8b56
dw OFFSET lblt_9b56
dw OFFSET lblt_10b56
dw OFFSET lblt_54b57
dw OFFSET lblt_55b57
dw OFFSET lblt_56b57
dw OFFSET lblt_57b57
dw OFFSET lblt_58b57
dw OFFSET lblt_59b57
dw OFFSET lblt_60b57
dw OFFSET lblt_61b57
dw OFFSET lblt_62b57
dw OFFSET lblt_63b57
dw OFFSET lblt_0b57
dw OFFSET lblt_1b57
dw OFFSET lblt_2b57
dw OFFSET lblt_3b57
dw OFFSET lblt_4b57
dw OFFSET lblt_5b57
dw OFFSET lblt_6b57
dw OFFSET lblt_7b57
dw OFFSET lblt_8b57
dw OFFSET lblt_9b57
dw OFFSET lblt_10b57
dw OFFSET lblt_54b58
dw OFFSET lblt_55b58
dw OFFSET lblt_56b58
dw OFFSET lblt_57b58
dw OFFSET lblt_58b58
dw OFFSET lblt_59b58
dw OFFSET lblt_60b58
dw OFFSET lblt_61b58
dw OFFSET lblt_62b58
dw OFFSET lblt_63b58
dw OFFSET lblt_0b58
dw OFFSET lblt_1b58
dw OFFSET lblt_2b58
dw OFFSET lblt_3b58
dw OFFSET lblt_4b58
dw OFFSET lblt_5b58
dw OFFSET lblt_6b58
dw OFFSET lblt_7b58
dw OFFSET lblt_8b58
dw OFFSET lblt_9b58
dw OFFSET lblt_10b58
dw OFFSET lblt_54b59
dw OFFSET lblt_55b59
dw OFFSET lblt_56b59
dw OFFSET lblt_57b59
dw OFFSET lblt_58b59
dw OFFSET lblt_59b59
dw OFFSET lblt_60b59
dw OFFSET lblt_61b59
dw OFFSET lblt_62b59
dw OFFSET lblt_63b59
dw OFFSET lblt_0b59
dw OFFSET lblt_1b59
dw OFFSET lblt_2b59
dw OFFSET lblt_3b59
dw OFFSET lblt_4b59
dw OFFSET lblt_5b59
dw OFFSET lblt_6b59
dw OFFSET lblt_7b59
dw OFFSET lblt_8b59
dw OFFSET lblt_9b59
dw OFFSET lblt_10b59
dw OFFSET lblt_54b60
dw OFFSET lblt_55b60
dw OFFSET lblt_56b60
dw OFFSET lblt_57b60
dw OFFSET lblt_58b60
dw OFFSET lblt_59b60
dw OFFSET lblt_60b60
dw OFFSET lblt_61b60
dw OFFSET lblt_62b60
dw OFFSET lblt_63b60
dw OFFSET lblt_0b60
dw OFFSET lblt_1b60
dw OFFSET lblt_2b60
dw OFFSET lblt_3b60
dw OFFSET lblt_4b60
dw OFFSET lblt_5b60
dw OFFSET lblt_6b60
dw OFFSET lblt_7b60
dw OFFSET lblt_8b60
dw OFFSET lblt_9b60
dw OFFSET lblt_10b60
dw OFFSET lblt_54b61
dw OFFSET lblt_55b61
dw OFFSET lblt_56b61
dw OFFSET lblt_57b61
dw OFFSET lblt_58b61
dw OFFSET lblt_59b61
dw OFFSET lblt_60b61
dw OFFSET lblt_61b61
dw OFFSET lblt_62b61
dw OFFSET lblt_63b61
dw OFFSET lblt_0b61
dw OFFSET lblt_1b61
dw OFFSET lblt_2b61
dw OFFSET lblt_3b61
dw OFFSET lblt_4b61
dw OFFSET lblt_5b61
dw OFFSET lblt_6b61
dw OFFSET lblt_7b61
dw OFFSET lblt_8b61
dw OFFSET lblt_9b61
dw OFFSET lblt_10b61
dw OFFSET lblt_54b62
dw OFFSET lblt_55b62
dw OFFSET lblt_56b62
dw OFFSET lblt_57b62
dw OFFSET lblt_58b62
dw OFFSET lblt_59b62
dw OFFSET lblt_60b62
dw OFFSET lblt_61b62
dw OFFSET lblt_62b62
dw OFFSET lblt_63b62
dw OFFSET lblt_0b62
dw OFFSET lblt_1b62
dw OFFSET lblt_2b62
dw OFFSET lblt_3b62
dw OFFSET lblt_4b62
dw OFFSET lblt_5b62
dw OFFSET lblt_6b62
dw OFFSET lblt_7b62
dw OFFSET lblt_8b62
dw OFFSET lblt_9b62
dw OFFSET lblt_10b62
dw OFFSET lblt_54b63
dw OFFSET lblt_55b63
dw OFFSET lblt_56b63
dw OFFSET lblt_57b63
dw OFFSET lblt_58b63
dw OFFSET lblt_59b63
dw OFFSET lblt_60b63
dw OFFSET lblt_61b63
dw OFFSET lblt_62b63
dw OFFSET lblt_63b63
dw OFFSET lblt_0b63
dw OFFSET lblt_1b63
dw OFFSET lblt_2b63
dw OFFSET lblt_3b63
dw OFFSET lblt_4b63
dw OFFSET lblt_5b63
dw OFFSET lblt_6b63
dw OFFSET lblt_7b63
dw OFFSET lblt_8b63
dw OFFSET lblt_9b63
dw OFFSET lblt_10b63
dw OFFSET lblt_54b0
dw OFFSET lblt_55b0
dw OFFSET lblt_56b0
dw OFFSET lblt_57b0
dw OFFSET lblt_58b0
dw OFFSET lblt_59b0
dw OFFSET lblt_60b0
dw OFFSET lblt_61b0
dw OFFSET lblt_62b0
dw OFFSET lblt_63b0
dw OFFSET lblt_0b0
dw OFFSET lblt_1b0
dw OFFSET lblt_2b0
dw OFFSET lblt_3b0
dw OFFSET lblt_4b0
dw OFFSET lblt_5b0
dw OFFSET lblt_6b0
dw OFFSET lblt_7b0
dw OFFSET lblt_8b0
dw OFFSET lblt_9b0
dw OFFSET lblt_10b0
dw OFFSET lblt_54b1
dw OFFSET lblt_55b1
dw OFFSET lblt_56b1
dw OFFSET lblt_57b1
dw OFFSET lblt_58b1
dw OFFSET lblt_59b1
dw OFFSET lblt_60b1
dw OFFSET lblt_61b1
dw OFFSET lblt_62b1
dw OFFSET lblt_63b1
dw OFFSET lblt_0b1
dw OFFSET lblt_1b1
dw OFFSET lblt_2b1
dw OFFSET lblt_3b1
dw OFFSET lblt_4b1
dw OFFSET lblt_5b1
dw OFFSET lblt_6b1
dw OFFSET lblt_7b1
dw OFFSET lblt_8b1
dw OFFSET lblt_9b1
dw OFFSET lblt_10b1
dw OFFSET lblt_54b2
dw OFFSET lblt_55b2
dw OFFSET lblt_56b2
dw OFFSET lblt_57b2
dw OFFSET lblt_58b2
dw OFFSET lblt_59b2
dw OFFSET lblt_60b2
dw OFFSET lblt_61b2
dw OFFSET lblt_62b2
dw OFFSET lblt_63b2
dw OFFSET lblt_0b2
dw OFFSET lblt_1b2
dw OFFSET lblt_2b2
dw OFFSET lblt_3b2
dw OFFSET lblt_4b2
dw OFFSET lblt_5b2
dw OFFSET lblt_6b2
dw OFFSET lblt_7b2
dw OFFSET lblt_8b2
dw OFFSET lblt_9b2
dw OFFSET lblt_10b2
dw OFFSET lblt_54b3
dw OFFSET lblt_55b3
dw OFFSET lblt_56b3
dw OFFSET lblt_57b3
dw OFFSET lblt_58b3
dw OFFSET lblt_59b3
dw OFFSET lblt_60b3
dw OFFSET lblt_61b3
dw OFFSET lblt_62b3
dw OFFSET lblt_63b3
dw OFFSET lblt_0b3
dw OFFSET lblt_1b3
dw OFFSET lblt_2b3
dw OFFSET lblt_3b3
dw OFFSET lblt_4b3
dw OFFSET lblt_5b3
dw OFFSET lblt_6b3
dw OFFSET lblt_7b3
dw OFFSET lblt_8b3
dw OFFSET lblt_9b3
dw OFFSET lblt_10b3
dw OFFSET lblt_54b4
dw OFFSET lblt_55b4
dw OFFSET lblt_56b4
dw OFFSET lblt_57b4
dw OFFSET lblt_58b4
dw OFFSET lblt_59b4
dw OFFSET lblt_60b4
dw OFFSET lblt_61b4
dw OFFSET lblt_62b4
dw OFFSET lblt_63b4
dw OFFSET lblt_0b4
dw OFFSET lblt_1b4
dw OFFSET lblt_2b4
dw OFFSET lblt_3b4
dw OFFSET lblt_4b4
dw OFFSET lblt_5b4
dw OFFSET lblt_6b4
dw OFFSET lblt_7b4
dw OFFSET lblt_8b4
dw OFFSET lblt_9b4
dw OFFSET lblt_10b4
dw OFFSET lblt_54b5
dw OFFSET lblt_55b5
dw OFFSET lblt_56b5
dw OFFSET lblt_57b5
dw OFFSET lblt_58b5
dw OFFSET lblt_59b5
dw OFFSET lblt_60b5
dw OFFSET lblt_61b5
dw OFFSET lblt_62b5
dw OFFSET lblt_63b5
dw OFFSET lblt_0b5
dw OFFSET lblt_1b5
dw OFFSET lblt_2b5
dw OFFSET lblt_3b5
dw OFFSET lblt_4b5
dw OFFSET lblt_5b5
dw OFFSET lblt_6b5
dw OFFSET lblt_7b5
dw OFFSET lblt_8b5
dw OFFSET lblt_9b5
dw OFFSET lblt_10b5
dw OFFSET lblt_54b6
dw OFFSET lblt_55b6
dw OFFSET lblt_56b6
dw OFFSET lblt_57b6
dw OFFSET lblt_58b6
dw OFFSET lblt_59b6
dw OFFSET lblt_60b6
dw OFFSET lblt_61b6
dw OFFSET lblt_62b6
dw OFFSET lblt_63b6
dw OFFSET lblt_0b6
dw OFFSET lblt_1b6
dw OFFSET lblt_2b6
dw OFFSET lblt_3b6
dw OFFSET lblt_4b6
dw OFFSET lblt_5b6
dw OFFSET lblt_6b6
dw OFFSET lblt_7b6
dw OFFSET lblt_8b6
dw OFFSET lblt_9b6
dw OFFSET lblt_10b6
dw OFFSET lblt_54b7
dw OFFSET lblt_55b7
dw OFFSET lblt_56b7
dw OFFSET lblt_57b7
dw OFFSET lblt_58b7
dw OFFSET lblt_59b7
dw OFFSET lblt_60b7
dw OFFSET lblt_61b7
dw OFFSET lblt_62b7
dw OFFSET lblt_63b7
dw OFFSET lblt_0b7
dw OFFSET lblt_1b7
dw OFFSET lblt_2b7
dw OFFSET lblt_3b7
dw OFFSET lblt_4b7
dw OFFSET lblt_5b7
dw OFFSET lblt_6b7
dw OFFSET lblt_7b7
dw OFFSET lblt_8b7
dw OFFSET lblt_9b7
dw OFFSET lblt_10b7
dw OFFSET lblt_54b8
dw OFFSET lblt_55b8
dw OFFSET lblt_56b8
dw OFFSET lblt_57b8
dw OFFSET lblt_58b8
dw OFFSET lblt_59b8
dw OFFSET lblt_60b8
dw OFFSET lblt_61b8
dw OFFSET lblt_62b8
dw OFFSET lblt_63b8
dw OFFSET lblt_0b8
dw OFFSET lblt_1b8
dw OFFSET lblt_2b8
dw OFFSET lblt_3b8
dw OFFSET lblt_4b8
dw OFFSET lblt_5b8
dw OFFSET lblt_6b8
dw OFFSET lblt_7b8
dw OFFSET lblt_8b8
dw OFFSET lblt_9b8
dw OFFSET lblt_10b8
lblt_54b56:
mov al,gs:[di+-2249]
xor al,dl
mov gs:[di+-2249],al
mov es:[di+-2249],al
mov ax,gs:[di+-1928]
xor ax,dx
mov gs:[di+-1928],ax
mov es:[di+-1928],ax
mov al,gs:[di+-1606]
xor al,dl
mov gs:[di+-1606],al
mov es:[di+-1606],al
mov al,gs:[di+-1285]
xor al,dl
mov gs:[di+-1285],al
mov es:[di+-1285],al
mov al,gs:[di+-964]
xor al,dl
mov gs:[di+-964],al
mov es:[di+-964],al
mov ax,gs:[di+-643]
xor ax,dx
mov gs:[di+-643],ax
mov es:[di+-643],ax
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_55b56:
mov al,gs:[di+-2248]
xor al,dl
mov gs:[di+-2248],al
mov es:[di+-2248],al
mov al,gs:[di+-1927]
xor al,dl
mov gs:[di+-1927],al
mov es:[di+-1927],al
mov al,gs:[di+-1606]
xor al,dl
mov gs:[di+-1606],al
mov es:[di+-1606],al
mov ax,gs:[di+-1285]
xor ax,dx
mov gs:[di+-1285],ax
mov es:[di+-1285],ax
mov al,gs:[di+-963]
xor al,dl
mov gs:[di+-963],al
mov es:[di+-963],al
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_56b56:
mov al,gs:[di+-2247]
xor al,dl
mov gs:[di+-2247],al
mov es:[di+-2247],al
mov al,gs:[di+-1926]
xor al,dl
mov gs:[di+-1926],al
mov es:[di+-1926],al
mov al,gs:[di+-1605]
xor al,dl
mov gs:[di+-1605],al
mov es:[di+-1605],al
mov al,gs:[di+-1284]
xor al,dl
mov gs:[di+-1284],al
mov es:[di+-1284],al
mov al,gs:[di+-963]
xor al,dl
mov gs:[di+-963],al
mov es:[di+-963],al
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_57b56:
mov al,gs:[di+-2246]
xor al,dl
mov gs:[di+-2246],al
mov es:[di+-2246],al
mov al,gs:[di+-1925]
xor al,dl
mov gs:[di+-1925],al
mov es:[di+-1925],al
mov al,gs:[di+-1604]
xor al,dl
mov gs:[di+-1604],al
mov es:[di+-1604],al
mov al,gs:[di+-1283]
xor al,dl
mov gs:[di+-1283],al
mov es:[di+-1283],al
mov al,gs:[di+-963]
xor al,dl
mov gs:[di+-963],al
mov es:[di+-963],al
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_58b56:
mov al,gs:[di+-2245]
xor al,dl
mov gs:[di+-2245],al
mov es:[di+-2245],al
mov al,gs:[di+-1924]
xor al,dl
mov gs:[di+-1924],al
mov es:[di+-1924],al
mov al,gs:[di+-1604]
xor al,dl
mov gs:[di+-1604],al
mov es:[di+-1604],al
mov al,gs:[di+-1283]
xor al,dl
mov gs:[di+-1283],al
mov es:[di+-1283],al
mov al,gs:[di+-962]
xor al,dl
mov gs:[di+-962],al
mov es:[di+-962],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_59b56:
mov al,gs:[di+-2244]
xor al,dl
mov gs:[di+-2244],al
mov es:[di+-2244],al
mov al,gs:[di+-1924]
xor al,dl
mov gs:[di+-1924],al
mov es:[di+-1924],al
mov al,gs:[di+-1603]
xor al,dl
mov gs:[di+-1603],al
mov es:[di+-1603],al
mov al,gs:[di+-1282]
xor al,dl
mov gs:[di+-1282],al
mov es:[di+-1282],al
mov al,gs:[di+-962]
xor al,dl
mov gs:[di+-962],al
mov es:[di+-962],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_60b56:
mov al,gs:[di+-2243]
xor al,dl
mov gs:[di+-2243],al
mov es:[di+-2243],al
mov al,gs:[di+-1923]
xor al,dl
mov gs:[di+-1923],al
mov es:[di+-1923],al
mov al,gs:[di+-1602]
xor al,dl
mov gs:[di+-1602],al
mov es:[di+-1602],al
mov al,gs:[di+-1282]
xor al,dl
mov gs:[di+-1282],al
mov es:[di+-1282],al
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_61b56:
mov al,gs:[di+-2243]
xor al,dl
mov gs:[di+-2243],al
mov es:[di+-2243],al
mov al,gs:[di+-1922]
xor al,dl
mov gs:[di+-1922],al
mov es:[di+-1922],al
mov al,gs:[di+-1602]
xor al,dl
mov gs:[di+-1602],al
mov es:[di+-1602],al
mov al,gs:[di+-1281]
xor al,dl
mov gs:[di+-1281],al
mov es:[di+-1281],al
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_62b56:
mov al,gs:[di+-2242]
xor al,dl
mov gs:[di+-2242],al
mov es:[di+-2242],al
mov al,gs:[di+-1921]
xor al,dl
mov gs:[di+-1921],al
mov es:[di+-1921],al
mov al,gs:[di+-1601]
xor al,dl
mov gs:[di+-1601],al
mov es:[di+-1601],al
mov al,gs:[di+-1281]
xor al,dl
mov gs:[di+-1281],al
mov es:[di+-1281],al
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_63b56:
mov al,gs:[di+-2241]
xor al,dl
mov gs:[di+-2241],al
mov es:[di+-2241],al
mov al,gs:[di+-1921]
xor al,dl
mov gs:[di+-1921],al
mov es:[di+-1921],al
mov al,gs:[di+-1601]
xor al,dl
mov gs:[di+-1601],al
mov es:[di+-1601],al
mov al,gs:[di+-1280]
xor al,dl
mov gs:[di+-1280],al
mov es:[di+-1280],al
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_0b56:
mov al,gs:[di+-2240]
xor al,dl
mov gs:[di+-2240],al
mov es:[di+-2240],al
mov al,gs:[di+-1920]
xor al,dl
mov gs:[di+-1920],al
mov es:[di+-1920],al
mov al,gs:[di+-1600]
xor al,dl
mov gs:[di+-1600],al
mov es:[di+-1600],al
mov al,gs:[di+-1280]
xor al,dl
mov gs:[di+-1280],al
mov es:[di+-1280],al
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_1b56:
mov al,gs:[di+-2239]
xor al,dl
mov gs:[di+-2239],al
mov es:[di+-2239],al
mov al,gs:[di+-1919]
xor al,dl
mov gs:[di+-1919],al
mov es:[di+-1919],al
mov al,gs:[di+-1599]
xor al,dl
mov gs:[di+-1599],al
mov es:[di+-1599],al
mov al,gs:[di+-1280]
xor al,dl
mov gs:[di+-1280],al
mov es:[di+-1280],al
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_2b56:
mov al,gs:[di+-2238]
xor al,dl
mov gs:[di+-2238],al
mov es:[di+-2238],al
mov al,gs:[di+-1919]
xor al,dl
mov gs:[di+-1919],al
mov es:[di+-1919],al
mov al,gs:[di+-1599]
xor al,dl
mov gs:[di+-1599],al
mov es:[di+-1599],al
mov al,gs:[di+-1279]
xor al,dl
mov gs:[di+-1279],al
mov es:[di+-1279],al
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_3b56:
mov al,gs:[di+-2237]
xor al,dl
mov gs:[di+-2237],al
mov es:[di+-2237],al
mov al,gs:[di+-1918]
xor al,dl
mov gs:[di+-1918],al
mov es:[di+-1918],al
mov al,gs:[di+-1598]
xor al,dl
mov gs:[di+-1598],al
mov es:[di+-1598],al
mov al,gs:[di+-1279]
xor al,dl
mov gs:[di+-1279],al
mov es:[di+-1279],al
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_4b56:
mov al,gs:[di+-2237]
xor al,dl
mov gs:[di+-2237],al
mov es:[di+-2237],al
mov al,gs:[di+-1917]
xor al,dl
mov gs:[di+-1917],al
mov es:[di+-1917],al
mov al,gs:[di+-1598]
xor al,dl
mov gs:[di+-1598],al
mov es:[di+-1598],al
mov al,gs:[di+-1278]
xor al,dl
mov gs:[di+-1278],al
mov es:[di+-1278],al
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_5b56:
mov al,gs:[di+-2236]
xor al,dl
mov gs:[di+-2236],al
mov es:[di+-2236],al
mov al,gs:[di+-1916]
xor al,dl
mov gs:[di+-1916],al
mov es:[di+-1916],al
mov al,gs:[di+-1597]
xor al,dl
mov gs:[di+-1597],al
mov es:[di+-1597],al
mov al,gs:[di+-1278]
xor al,dl
mov gs:[di+-1278],al
mov es:[di+-1278],al
mov al,gs:[di+-958]
xor al,dl
mov gs:[di+-958],al
mov es:[di+-958],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_6b56:
mov al,gs:[di+-2235]
xor al,dl
mov gs:[di+-2235],al
mov es:[di+-2235],al
mov al,gs:[di+-1916]
xor al,dl
mov gs:[di+-1916],al
mov es:[di+-1916],al
mov al,gs:[di+-1596]
xor al,dl
mov gs:[di+-1596],al
mov es:[di+-1596],al
mov al,gs:[di+-1277]
xor al,dl
mov gs:[di+-1277],al
mov es:[di+-1277],al
mov al,gs:[di+-958]
xor al,dl
mov gs:[di+-958],al
mov es:[di+-958],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_7b56:
mov al,gs:[di+-2234]
xor al,dl
mov gs:[di+-2234],al
mov es:[di+-2234],al
mov al,gs:[di+-1915]
xor al,dl
mov gs:[di+-1915],al
mov es:[di+-1915],al
mov al,gs:[di+-1596]
xor al,dl
mov gs:[di+-1596],al
mov es:[di+-1596],al
mov al,gs:[di+-1277]
xor al,dl
mov gs:[di+-1277],al
mov es:[di+-1277],al
mov al,gs:[di+-957]
xor al,dl
mov gs:[di+-957],al
mov es:[di+-957],al
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_8b56:
mov al,gs:[di+-2233]
xor al,dl
mov gs:[di+-2233],al
mov es:[di+-2233],al
mov al,gs:[di+-1914]
xor al,dl
mov gs:[di+-1914],al
mov es:[di+-1914],al
mov al,gs:[di+-1595]
xor al,dl
mov gs:[di+-1595],al
mov es:[di+-1595],al
mov al,gs:[di+-1276]
xor al,dl
mov gs:[di+-1276],al
mov es:[di+-1276],al
mov al,gs:[di+-957]
xor al,dl
mov gs:[di+-957],al
mov es:[di+-957],al
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_9b56:
mov al,gs:[di+-2232]
xor al,dl
mov gs:[di+-2232],al
mov es:[di+-2232],al
mov al,gs:[di+-1913]
xor al,dl
mov gs:[di+-1913],al
mov es:[di+-1913],al
mov al,gs:[di+-1594]
xor al,dl
mov gs:[di+-1594],al
mov es:[di+-1594],al
mov ax,gs:[di+-1276]
xor ax,dx
mov gs:[di+-1276],ax
mov es:[di+-1276],ax
mov al,gs:[di+-957]
xor al,dl
mov gs:[di+-957],al
mov es:[di+-957],al
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_10b56:
mov al,gs:[di+-2231]
xor al,dl
mov gs:[di+-2231],al
mov es:[di+-2231],al
mov ax,gs:[di+-1913]
xor ax,dx
mov gs:[di+-1913],ax
mov es:[di+-1913],ax
mov al,gs:[di+-1594]
xor al,dl
mov gs:[di+-1594],al
mov es:[di+-1594],al
mov al,gs:[di+-1275]
xor al,dl
mov gs:[di+-1275],al
mov es:[di+-1275],al
mov al,gs:[di+-956]
xor al,dl
mov gs:[di+-956],al
mov es:[di+-956],al
mov ax,gs:[di+-638]
xor ax,dx
mov gs:[di+-638],ax
mov es:[di+-638],ax
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_54b57:
mov ax,gs:[di+-1929]
xor ax,dx
mov gs:[di+-1929],ax
mov es:[di+-1929],ax
mov al,gs:[di+-1607]
xor al,dl
mov gs:[di+-1607],al
mov es:[di+-1607],al
mov al,gs:[di+-1286]
xor al,dl
mov gs:[di+-1286],al
mov es:[di+-1286],al
mov ax,gs:[di+-965]
xor ax,dx
mov gs:[di+-965],ax
mov es:[di+-965],ax
mov al,gs:[di+-643]
xor al,dl
mov gs:[di+-643],al
mov es:[di+-643],al
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_55b57:
mov al,gs:[di+-1928]
xor al,dl
mov gs:[di+-1928],al
mov es:[di+-1928],al
mov ax,gs:[di+-1607]
xor ax,dx
mov gs:[di+-1607],ax
mov es:[di+-1607],ax
mov al,gs:[di+-1285]
xor al,dl
mov gs:[di+-1285],al
mov es:[di+-1285],al
mov al,gs:[di+-964]
xor al,dl
mov gs:[di+-964],al
mov es:[di+-964],al
mov ax,gs:[di+-643]
xor ax,dx
mov gs:[di+-643],ax
mov es:[di+-643],ax
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_56b57:
mov al,gs:[di+-1927]
xor al,dl
mov gs:[di+-1927],al
mov es:[di+-1927],al
mov al,gs:[di+-1606]
xor al,dl
mov gs:[di+-1606],al
mov es:[di+-1606],al
mov al,gs:[di+-1285]
xor al,dl
mov gs:[di+-1285],al
mov es:[di+-1285],al
mov ax,gs:[di+-964]
xor ax,dx
mov gs:[di+-964],ax
mov es:[di+-964],ax
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_57b57:
mov al,gs:[di+-1926]
xor al,dl
mov gs:[di+-1926],al
mov es:[di+-1926],al
mov al,gs:[di+-1605]
xor al,dl
mov gs:[di+-1605],al
mov es:[di+-1605],al
mov al,gs:[di+-1284]
xor al,dl
mov gs:[di+-1284],al
mov es:[di+-1284],al
mov al,gs:[di+-963]
xor al,dl
mov gs:[di+-963],al
mov es:[di+-963],al
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_58b57:
mov al,gs:[di+-1925]
xor al,dl
mov gs:[di+-1925],al
mov es:[di+-1925],al
mov al,gs:[di+-1604]
xor al,dl
mov gs:[di+-1604],al
mov es:[di+-1604],al
mov al,gs:[di+-1283]
xor al,dl
mov gs:[di+-1283],al
mov es:[di+-1283],al
mov al,gs:[di+-963]
xor al,dl
mov gs:[di+-963],al
mov es:[di+-963],al
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_59b57:
mov al,gs:[di+-1924]
xor al,dl
mov gs:[di+-1924],al
mov es:[di+-1924],al
mov al,gs:[di+-1604]
xor al,dl
mov gs:[di+-1604],al
mov es:[di+-1604],al
mov al,gs:[di+-1283]
xor al,dl
mov gs:[di+-1283],al
mov es:[di+-1283],al
mov al,gs:[di+-962]
xor al,dl
mov gs:[di+-962],al
mov es:[di+-962],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_60b57:
mov al,gs:[di+-1923]
xor al,dl
mov gs:[di+-1923],al
mov es:[di+-1923],al
mov al,gs:[di+-1603]
xor al,dl
mov gs:[di+-1603],al
mov es:[di+-1603],al
mov al,gs:[di+-1282]
xor al,dl
mov gs:[di+-1282],al
mov es:[di+-1282],al
mov al,gs:[di+-962]
xor al,dl
mov gs:[di+-962],al
mov es:[di+-962],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_61b57:
mov al,gs:[di+-1923]
xor al,dl
mov gs:[di+-1923],al
mov es:[di+-1923],al
mov al,gs:[di+-1602]
xor al,dl
mov gs:[di+-1602],al
mov es:[di+-1602],al
mov al,gs:[di+-1282]
xor al,dl
mov gs:[di+-1282],al
mov es:[di+-1282],al
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_62b57:
mov al,gs:[di+-1922]
xor al,dl
mov gs:[di+-1922],al
mov es:[di+-1922],al
mov al,gs:[di+-1601]
xor al,dl
mov gs:[di+-1601],al
mov es:[di+-1601],al
mov al,gs:[di+-1281]
xor al,dl
mov gs:[di+-1281],al
mov es:[di+-1281],al
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_63b57:
mov al,gs:[di+-1921]
xor al,dl
mov gs:[di+-1921],al
mov es:[di+-1921],al
mov al,gs:[di+-1601]
xor al,dl
mov gs:[di+-1601],al
mov es:[di+-1601],al
mov al,gs:[di+-1281]
xor al,dl
mov gs:[di+-1281],al
mov es:[di+-1281],al
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_0b57:
mov al,gs:[di+-1920]
xor al,dl
mov gs:[di+-1920],al
mov es:[di+-1920],al
mov al,gs:[di+-1600]
xor al,dl
mov gs:[di+-1600],al
mov es:[di+-1600],al
mov al,gs:[di+-1280]
xor al,dl
mov gs:[di+-1280],al
mov es:[di+-1280],al
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_1b57:
mov al,gs:[di+-1919]
xor al,dl
mov gs:[di+-1919],al
mov es:[di+-1919],al
mov al,gs:[di+-1599]
xor al,dl
mov gs:[di+-1599],al
mov es:[di+-1599],al
mov al,gs:[di+-1279]
xor al,dl
mov gs:[di+-1279],al
mov es:[di+-1279],al
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_2b57:
mov al,gs:[di+-1918]
xor al,dl
mov gs:[di+-1918],al
mov es:[di+-1918],al
mov al,gs:[di+-1599]
xor al,dl
mov gs:[di+-1599],al
mov es:[di+-1599],al
mov al,gs:[di+-1279]
xor al,dl
mov gs:[di+-1279],al
mov es:[di+-1279],al
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_3b57:
mov al,gs:[di+-1917]
xor al,dl
mov gs:[di+-1917],al
mov es:[di+-1917],al
mov al,gs:[di+-1598]
xor al,dl
mov gs:[di+-1598],al
mov es:[di+-1598],al
mov al,gs:[di+-1278]
xor al,dl
mov gs:[di+-1278],al
mov es:[di+-1278],al
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_4b57:
mov al,gs:[di+-1917]
xor al,dl
mov gs:[di+-1917],al
mov es:[di+-1917],al
mov al,gs:[di+-1597]
xor al,dl
mov gs:[di+-1597],al
mov es:[di+-1597],al
mov al,gs:[di+-1278]
xor al,dl
mov gs:[di+-1278],al
mov es:[di+-1278],al
mov al,gs:[di+-958]
xor al,dl
mov gs:[di+-958],al
mov es:[di+-958],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_5b57:
mov al,gs:[di+-1916]
xor al,dl
mov gs:[di+-1916],al
mov es:[di+-1916],al
mov al,gs:[di+-1596]
xor al,dl
mov gs:[di+-1596],al
mov es:[di+-1596],al
mov al,gs:[di+-1277]
xor al,dl
mov gs:[di+-1277],al
mov es:[di+-1277],al
mov al,gs:[di+-958]
xor al,dl
mov gs:[di+-958],al
mov es:[di+-958],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_6b57:
mov al,gs:[di+-1915]
xor al,dl
mov gs:[di+-1915],al
mov es:[di+-1915],al
mov al,gs:[di+-1596]
xor al,dl
mov gs:[di+-1596],al
mov es:[di+-1596],al
mov al,gs:[di+-1277]
xor al,dl
mov gs:[di+-1277],al
mov es:[di+-1277],al
mov al,gs:[di+-957]
xor al,dl
mov gs:[di+-957],al
mov es:[di+-957],al
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_7b57:
mov al,gs:[di+-1914]
xor al,dl
mov gs:[di+-1914],al
mov es:[di+-1914],al
mov al,gs:[di+-1595]
xor al,dl
mov gs:[di+-1595],al
mov es:[di+-1595],al
mov al,gs:[di+-1276]
xor al,dl
mov gs:[di+-1276],al
mov es:[di+-1276],al
mov al,gs:[di+-957]
xor al,dl
mov gs:[di+-957],al
mov es:[di+-957],al
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_8b57:
mov al,gs:[di+-1913]
xor al,dl
mov gs:[di+-1913],al
mov es:[di+-1913],al
mov al,gs:[di+-1594]
xor al,dl
mov gs:[di+-1594],al
mov es:[di+-1594],al
mov al,gs:[di+-1275]
xor al,dl
mov gs:[di+-1275],al
mov es:[di+-1275],al
mov ax,gs:[di+-957]
xor ax,dx
mov gs:[di+-957],ax
mov es:[di+-957],ax
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_9b57:
mov al,gs:[di+-1912]
xor al,dl
mov gs:[di+-1912],al
mov es:[di+-1912],al
mov ax,gs:[di+-1594]
xor ax,dx
mov gs:[di+-1594],ax
mov es:[di+-1594],ax
mov al,gs:[di+-1275]
xor al,dl
mov gs:[di+-1275],al
mov es:[di+-1275],al
mov al,gs:[di+-956]
xor al,dl
mov gs:[di+-956],al
mov es:[di+-956],al
mov ax,gs:[di+-638]
xor ax,dx
mov gs:[di+-638],ax
mov es:[di+-638],ax
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_10b57:
mov ax,gs:[di+-1912]
xor ax,dx
mov gs:[di+-1912],ax
mov es:[di+-1912],ax
mov al,gs:[di+-1593]
xor al,dl
mov gs:[di+-1593],al
mov es:[di+-1593],al
mov al,gs:[di+-1274]
xor al,dl
mov gs:[di+-1274],al
mov es:[di+-1274],al
mov ax,gs:[di+-956]
xor ax,dx
mov gs:[di+-956],ax
mov es:[di+-956],ax
mov al,gs:[di+-637]
xor al,dl
mov gs:[di+-637],al
mov es:[di+-637],al
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_54b58:
mov ax,gs:[di+-1609]
xor ax,dx
mov gs:[di+-1609],ax
mov es:[di+-1609],ax
mov ax,gs:[di+-1287]
xor ax,dx
mov gs:[di+-1287],ax
mov es:[di+-1287],ax
mov al,gs:[di+-965]
xor al,dl
mov gs:[di+-965],al
mov es:[di+-965],al
mov ax,gs:[di+-644]
xor ax,dx
mov gs:[di+-644],ax
mov es:[di+-644],ax
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_55b58:
mov ax,gs:[di+-1608]
xor ax,dx
mov gs:[di+-1608],ax
mov es:[di+-1608],ax
mov al,gs:[di+-1286]
xor al,dl
mov gs:[di+-1286],al
mov es:[di+-1286],al
mov ax,gs:[di+-965]
xor ax,dx
mov gs:[di+-965],ax
mov es:[di+-965],ax
mov al,gs:[di+-643]
xor al,dl
mov gs:[di+-643],al
mov es:[di+-643],al
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_56b58:
mov al,gs:[di+-1607]
xor al,dl
mov gs:[di+-1607],al
mov es:[di+-1607],al
mov ax,gs:[di+-1286]
xor ax,dx
mov gs:[di+-1286],ax
mov es:[di+-1286],ax
mov al,gs:[di+-964]
xor al,dl
mov gs:[di+-964],al
mov es:[di+-964],al
mov al,gs:[di+-643]
xor al,dl
mov gs:[di+-643],al
mov es:[di+-643],al
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_57b58:
mov al,gs:[di+-1606]
xor al,dl
mov gs:[di+-1606],al
mov es:[di+-1606],al
mov al,gs:[di+-1285]
xor al,dl
mov gs:[di+-1285],al
mov es:[di+-1285],al
mov ax,gs:[di+-964]
xor ax,dx
mov gs:[di+-964],ax
mov es:[di+-964],ax
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_58b58:
mov al,gs:[di+-1605]
xor al,dl
mov gs:[di+-1605],al
mov es:[di+-1605],al
mov al,gs:[di+-1284]
xor al,dl
mov gs:[di+-1284],al
mov es:[di+-1284],al
mov al,gs:[di+-963]
xor al,dl
mov gs:[di+-963],al
mov es:[di+-963],al
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_59b58:
mov al,gs:[di+-1604]
xor al,dl
mov gs:[di+-1604],al
mov es:[di+-1604],al
mov al,gs:[di+-1283]
xor al,dl
mov gs:[di+-1283],al
mov es:[di+-1283],al
mov al,gs:[di+-962]
xor al,dl
mov gs:[di+-962],al
mov es:[di+-962],al
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_60b58:
mov al,gs:[di+-1603]
xor al,dl
mov gs:[di+-1603],al
mov es:[di+-1603],al
mov al,gs:[di+-1283]
xor al,dl
mov gs:[di+-1283],al
mov es:[di+-1283],al
mov al,gs:[di+-962]
xor al,dl
mov gs:[di+-962],al
mov es:[di+-962],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_61b58:
mov al,gs:[di+-1602]
xor al,dl
mov gs:[di+-1602],al
mov es:[di+-1602],al
mov al,gs:[di+-1282]
xor al,dl
mov gs:[di+-1282],al
mov es:[di+-1282],al
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_62b58:
mov al,gs:[di+-1602]
xor al,dl
mov gs:[di+-1602],al
mov es:[di+-1602],al
mov al,gs:[di+-1281]
xor al,dl
mov gs:[di+-1281],al
mov es:[di+-1281],al
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_63b58:
mov al,gs:[di+-1601]
xor al,dl
mov gs:[di+-1601],al
mov es:[di+-1601],al
mov al,gs:[di+-1281]
xor al,dl
mov gs:[di+-1281],al
mov es:[di+-1281],al
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_0b58:
mov al,gs:[di+-1600]
xor al,dl
mov gs:[di+-1600],al
mov es:[di+-1600],al
mov al,gs:[di+-1280]
xor al,dl
mov gs:[di+-1280],al
mov es:[di+-1280],al
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_1b58:
mov al,gs:[di+-1599]
xor al,dl
mov gs:[di+-1599],al
mov es:[di+-1599],al
mov al,gs:[di+-1279]
xor al,dl
mov gs:[di+-1279],al
mov es:[di+-1279],al
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_2b58:
mov al,gs:[di+-1598]
xor al,dl
mov gs:[di+-1598],al
mov es:[di+-1598],al
mov al,gs:[di+-1279]
xor al,dl
mov gs:[di+-1279],al
mov es:[di+-1279],al
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_3b58:
mov al,gs:[di+-1598]
xor al,dl
mov gs:[di+-1598],al
mov es:[di+-1598],al
mov al,gs:[di+-1278]
xor al,dl
mov gs:[di+-1278],al
mov es:[di+-1278],al
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_4b58:
mov al,gs:[di+-1597]
xor al,dl
mov gs:[di+-1597],al
mov es:[di+-1597],al
mov al,gs:[di+-1277]
xor al,dl
mov gs:[di+-1277],al
mov es:[di+-1277],al
mov al,gs:[di+-958]
xor al,dl
mov gs:[di+-958],al
mov es:[di+-958],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_5b58:
mov al,gs:[di+-1596]
xor al,dl
mov gs:[di+-1596],al
mov es:[di+-1596],al
mov al,gs:[di+-1277]
xor al,dl
mov gs:[di+-1277],al
mov es:[di+-1277],al
mov al,gs:[di+-958]
xor al,dl
mov gs:[di+-958],al
mov es:[di+-958],al
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_6b58:
mov al,gs:[di+-1595]
xor al,dl
mov gs:[di+-1595],al
mov es:[di+-1595],al
mov al,gs:[di+-1276]
xor al,dl
mov gs:[di+-1276],al
mov es:[di+-1276],al
mov al,gs:[di+-957]
xor al,dl
mov gs:[di+-957],al
mov es:[di+-957],al
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_7b58:
mov al,gs:[di+-1594]
xor al,dl
mov gs:[di+-1594],al
mov es:[di+-1594],al
mov al,gs:[di+-1275]
xor al,dl
mov gs:[di+-1275],al
mov es:[di+-1275],al
mov ax,gs:[di+-957]
xor ax,dx
mov gs:[di+-957],ax
mov es:[di+-957],ax
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_8b58:
mov al,gs:[di+-1593]
xor al,dl
mov gs:[di+-1593],al
mov es:[di+-1593],al
mov ax,gs:[di+-1275]
xor ax,dx
mov gs:[di+-1275],ax
mov es:[di+-1275],ax
mov al,gs:[di+-956]
xor al,dl
mov gs:[di+-956],al
mov es:[di+-956],al
mov al,gs:[di+-637]
xor al,dl
mov gs:[di+-637],al
mov es:[di+-637],al
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_9b58:
mov ax,gs:[di+-1593]
xor ax,dx
mov gs:[di+-1593],ax
mov es:[di+-1593],ax
mov al,gs:[di+-1274]
xor al,dl
mov gs:[di+-1274],al
mov es:[di+-1274],al
mov ax,gs:[di+-956]
xor ax,dx
mov gs:[di+-956],ax
mov es:[di+-956],ax
mov al,gs:[di+-637]
xor al,dl
mov gs:[di+-637],al
mov es:[di+-637],al
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_10b58:
mov ax,gs:[di+-1592]
xor ax,dx
mov gs:[di+-1592],ax
mov es:[di+-1592],ax
mov ax,gs:[di+-1274]
xor ax,dx
mov gs:[di+-1274],ax
mov es:[di+-1274],ax
mov al,gs:[di+-955]
xor al,dl
mov gs:[di+-955],al
mov es:[di+-955],al
mov ax,gs:[di+-637]
xor ax,dx
mov gs:[di+-637],ax
mov es:[di+-637],ax
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_54b59:
mov ax,gs:[di+-1289]
xor ax,dx
mov gs:[di+-1289],ax
mov es:[di+-1289],ax
mov ax,gs:[di+-967]
xor ax,dx
mov gs:[di+-967],ax
mov es:[di+-967],ax
mov ax,gs:[di+-645]
xor ax,dx
mov gs:[di+-645],ax
mov es:[di+-645],ax
mov ax,gs:[di+-323]
xor ax,dx
mov gs:[di+-323],ax
mov es:[di+-323],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_55b59:
mov ax,gs:[di+-1288]
xor ax,dx
mov gs:[di+-1288],ax
mov es:[di+-1288],ax
mov ax,gs:[di+-966]
xor ax,dx
mov gs:[di+-966],ax
mov es:[di+-966],ax
mov ax,gs:[di+-644]
xor ax,dx
mov gs:[di+-644],ax
mov es:[di+-644],ax
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_56b59:
mov ax,gs:[di+-1287]
xor ax,dx
mov gs:[di+-1287],ax
mov es:[di+-1287],ax
mov al,gs:[di+-965]
xor al,dl
mov gs:[di+-965],al
mov es:[di+-965],al
mov ax,gs:[di+-644]
xor ax,dx
mov gs:[di+-644],ax
mov es:[di+-644],ax
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_57b59:
mov ax,gs:[di+-1286]
xor ax,dx
mov gs:[di+-1286],ax
mov es:[di+-1286],ax
mov al,gs:[di+-964]
xor al,dl
mov gs:[di+-964],al
mov es:[di+-964],al
mov al,gs:[di+-643]
xor al,dl
mov gs:[di+-643],al
mov es:[di+-643],al
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_58b59:
mov al,gs:[di+-1285]
xor al,dl
mov gs:[di+-1285],al
mov es:[di+-1285],al
mov al,gs:[di+-964]
xor al,dl
mov gs:[di+-964],al
mov es:[di+-964],al
mov ax,gs:[di+-643]
xor ax,dx
mov gs:[di+-643],ax
mov es:[di+-643],ax
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_59b59:
mov al,gs:[di+-1284]
xor al,dl
mov gs:[di+-1284],al
mov es:[di+-1284],al
mov al,gs:[di+-963]
xor al,dl
mov gs:[di+-963],al
mov es:[di+-963],al
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_60b59:
mov al,gs:[di+-1283]
xor al,dl
mov gs:[di+-1283],al
mov es:[di+-1283],al
mov al,gs:[di+-962]
xor al,dl
mov gs:[di+-962],al
mov es:[di+-962],al
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_61b59:
mov al,gs:[di+-1282]
xor al,dl
mov gs:[di+-1282],al
mov es:[di+-1282],al
mov al,gs:[di+-962]
xor al,dl
mov gs:[di+-962],al
mov es:[di+-962],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_62b59:
mov al,gs:[di+-1282]
xor al,dl
mov gs:[di+-1282],al
mov es:[di+-1282],al
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_63b59:
mov al,gs:[di+-1281]
xor al,dl
mov gs:[di+-1281],al
mov es:[di+-1281],al
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_0b59:
mov al,gs:[di+-1280]
xor al,dl
mov gs:[di+-1280],al
mov es:[di+-1280],al
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_1b59:
mov al,gs:[di+-1279]
xor al,dl
mov gs:[di+-1279],al
mov es:[di+-1279],al
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_2b59:
mov al,gs:[di+-1278]
xor al,dl
mov gs:[di+-1278],al
mov es:[di+-1278],al
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_3b59:
mov al,gs:[di+-1278]
xor al,dl
mov gs:[di+-1278],al
mov es:[di+-1278],al
mov al,gs:[di+-958]
xor al,dl
mov gs:[di+-958],al
mov es:[di+-958],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_4b59:
mov al,gs:[di+-1277]
xor al,dl
mov gs:[di+-1277],al
mov es:[di+-1277],al
mov al,gs:[di+-958]
xor al,dl
mov gs:[di+-958],al
mov es:[di+-958],al
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_5b59:
mov al,gs:[di+-1276]
xor al,dl
mov gs:[di+-1276],al
mov es:[di+-1276],al
mov al,gs:[di+-957]
xor al,dl
mov gs:[di+-957],al
mov es:[di+-957],al
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_6b59:
mov al,gs:[di+-1275]
xor al,dl
mov gs:[di+-1275],al
mov es:[di+-1275],al
mov al,gs:[di+-956]
xor al,dl
mov gs:[di+-956],al
mov es:[di+-956],al
mov ax,gs:[di+-638]
xor ax,dx
mov gs:[di+-638],ax
mov es:[di+-638],ax
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_7b59:
mov ax,gs:[di+-1275]
xor ax,dx
mov gs:[di+-1275],ax
mov es:[di+-1275],ax
mov al,gs:[di+-956]
xor al,dl
mov gs:[di+-956],al
mov es:[di+-956],al
mov al,gs:[di+-637]
xor al,dl
mov gs:[di+-637],al
mov es:[di+-637],al
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_8b59:
mov ax,gs:[di+-1274]
xor ax,dx
mov gs:[di+-1274],ax
mov es:[di+-1274],ax
mov al,gs:[di+-955]
xor al,dl
mov gs:[di+-955],al
mov es:[di+-955],al
mov ax,gs:[di+-637]
xor ax,dx
mov gs:[di+-637],ax
mov es:[di+-637],ax
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_9b59:
mov ax,gs:[di+-1273]
xor ax,dx
mov gs:[di+-1273],ax
mov es:[di+-1273],ax
mov ax,gs:[di+-955]
xor ax,dx
mov gs:[di+-955],ax
mov es:[di+-955],ax
mov ax,gs:[di+-637]
xor ax,dx
mov gs:[di+-637],ax
mov es:[di+-637],ax
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_10b59:
mov ax,gs:[di+-1272]
xor ax,dx
mov gs:[di+-1272],ax
mov es:[di+-1272],ax
mov ax,gs:[di+-954]
xor ax,dx
mov gs:[di+-954],ax
mov es:[di+-954],ax
mov ax,gs:[di+-636]
xor ax,dx
mov gs:[di+-636],ax
mov es:[di+-636],ax
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_54b60:
mov al,gs:[di+-1289]
xor al,dl
mov gs:[di+-1289],al
mov es:[di+-1289],al
mov ax,gs:[di+-968]
xor ax,dx
mov gs:[di+-968],ax
mov es:[di+-968],ax
mov ax,gs:[di+-646]
xor ax,dx
mov gs:[di+-646],ax
mov es:[di+-646],ax
mov al,gs:[di+-644]
xor al,dl
mov gs:[di+-644],al
mov es:[di+-644],al
mov ax,gs:[di+-323]
xor ax,dx
mov gs:[di+-323],ax
mov es:[di+-323],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_55b60:
mov al,gs:[di+-1288]
xor al,dl
mov gs:[di+-1288],al
mov es:[di+-1288],al
mov ax,gs:[di+-967]
xor ax,dx
mov gs:[di+-967],ax
mov es:[di+-967],ax
mov ax,gs:[di+-645]
xor ax,dx
mov gs:[di+-645],ax
mov es:[di+-645],ax
mov ax,gs:[di+-323]
xor ax,dx
mov gs:[di+-323],ax
mov es:[di+-323],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_56b60:
mov ax,gs:[di+-967]
xor ax,dx
mov gs:[di+-967],ax
mov es:[di+-967],ax
mov ax,gs:[di+-645]
xor ax,dx
mov gs:[di+-645],ax
mov es:[di+-645],ax
mov ax,gs:[di+-323]
xor ax,dx
mov gs:[di+-323],ax
mov es:[di+-323],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_57b60:
mov ax,gs:[di+-966]
xor ax,dx
mov gs:[di+-966],ax
mov es:[di+-966],ax
mov ax,gs:[di+-644]
xor ax,dx
mov gs:[di+-644],ax
mov es:[di+-644],ax
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_58b60:
mov ax,gs:[di+-965]
xor ax,dx
mov gs:[di+-965],ax
mov es:[di+-965],ax
mov al,gs:[di+-643]
xor al,dl
mov gs:[di+-643],al
mov es:[di+-643],al
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_59b60:
mov al,gs:[di+-964]
xor al,dl
mov gs:[di+-964],al
mov es:[di+-964],al
mov ax,gs:[di+-643]
xor ax,dx
mov gs:[di+-643],ax
mov es:[di+-643],ax
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_60b60:
mov al,gs:[di+-963]
xor al,dl
mov gs:[di+-963],al
mov es:[di+-963],al
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_61b60:
mov al,gs:[di+-962]
xor al,dl
mov gs:[di+-962],al
mov es:[di+-962],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_62b60:
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_63b60:
mov al,gs:[di+-961]
xor al,dl
mov gs:[di+-961],al
mov es:[di+-961],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_0b60:
mov al,gs:[di+-960]
xor al,dl
mov gs:[di+-960],al
mov es:[di+-960],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_1b60:
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_2b60:
mov al,gs:[di+-959]
xor al,dl
mov gs:[di+-959],al
mov es:[di+-959],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_3b60:
mov al,gs:[di+-958]
xor al,dl
mov gs:[di+-958],al
mov es:[di+-958],al
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_4b60:
mov al,gs:[di+-957]
xor al,dl
mov gs:[di+-957],al
mov es:[di+-957],al
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_5b60:
mov al,gs:[di+-956]
xor al,dl
mov gs:[di+-956],al
mov es:[di+-956],al
mov ax,gs:[di+-638]
xor ax,dx
mov gs:[di+-638],ax
mov es:[di+-638],ax
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_6b60:
mov ax,gs:[di+-956]
xor ax,dx
mov gs:[di+-956],ax
mov es:[di+-956],ax
mov al,gs:[di+-637]
xor al,dl
mov gs:[di+-637],al
mov es:[di+-637],al
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_7b60:
mov ax,gs:[di+-955]
xor ax,dx
mov gs:[di+-955],ax
mov es:[di+-955],ax
mov ax,gs:[di+-637]
xor ax,dx
mov gs:[di+-637],ax
mov es:[di+-637],ax
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_8b60:
mov ax,gs:[di+-954]
xor ax,dx
mov gs:[di+-954],ax
mov es:[di+-954],ax
mov ax,gs:[di+-636]
xor ax,dx
mov gs:[di+-636],ax
mov es:[di+-636],ax
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_9b60:
mov al,gs:[di+-1272]
xor al,dl
mov gs:[di+-1272],al
mov es:[di+-1272],al
mov ax,gs:[di+-954]
xor ax,dx
mov gs:[di+-954],ax
mov es:[di+-954],ax
mov ax,gs:[di+-636]
xor ax,dx
mov gs:[di+-636],ax
mov es:[di+-636],ax
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_10b60:
mov al,gs:[di+-1271]
xor al,dl
mov gs:[di+-1271],al
mov es:[di+-1271],al
mov ax,gs:[di+-953]
xor ax,dx
mov gs:[di+-953],ax
mov es:[di+-953],ax
mov ax,gs:[di+-636]
xor ax,dx
mov gs:[di+-636],ax
mov es:[di+-636],ax
mov al,gs:[di+-634]
xor al,dl
mov gs:[di+-634],al
mov es:[di+-634],al
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_54b61:
mov al,gs:[di+-969]
xor al,dl
mov gs:[di+-969],al
mov es:[di+-969],al
mov ax,gs:[di+-648]
xor ax,dx
mov gs:[di+-648],ax
mov es:[di+-648],ax
mov al,gs:[di+-646]
xor al,dl
mov gs:[di+-646],al
mov es:[di+-646],al
mov ax,gs:[di+-325]
xor ax,dx
mov gs:[di+-325],ax
mov es:[di+-325],ax
mov ax,gs:[di+-323]
xor ax,dx
mov gs:[di+-323],ax
mov es:[di+-323],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_55b61:
mov al,gs:[di+-968]
xor al,dl
mov gs:[di+-968],al
mov es:[di+-968],al
mov ax,gs:[di+-647]
xor ax,dx
mov gs:[di+-647],ax
mov es:[di+-647],ax
mov al,gs:[di+-645]
xor al,dl
mov gs:[di+-645],al
mov es:[di+-645],al
mov ax,gs:[di+-324]
xor ax,dx
mov gs:[di+-324],ax
mov es:[di+-324],ax
mov al,gs:[di+-322]
xor al,dl
mov gs:[di+-322],al
mov es:[di+-322],al
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_56b61:
mov al,gs:[di+-967]
xor al,dl
mov gs:[di+-967],al
mov es:[di+-967],al
mov ax,gs:[di+-646]
xor ax,dx
mov gs:[di+-646],ax
mov es:[di+-646],ax
mov ax,gs:[di+-324]
xor ax,dx
mov gs:[di+-324],ax
mov es:[di+-324],ax
mov al,gs:[di+-322]
xor al,dl
mov gs:[di+-322],al
mov es:[di+-322],al
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_57b61:
mov al,gs:[di+-966]
xor al,dl
mov gs:[di+-966],al
mov es:[di+-966],al
mov ax,gs:[di+-645]
xor ax,dx
mov gs:[di+-645],ax
mov es:[di+-645],ax
mov ax,gs:[di+-323]
xor ax,dx
mov gs:[di+-323],ax
mov es:[di+-323],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_58b61:
mov ax,gs:[di+-645]
xor ax,dx
mov gs:[di+-645],ax
mov es:[di+-645],ax
mov ax,gs:[di+-323]
xor ax,dx
mov gs:[di+-323],ax
mov es:[di+-323],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_59b61:
mov ax,gs:[di+-644]
xor ax,dx
mov gs:[di+-644],ax
mov es:[di+-644],ax
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_60b61:
mov al,gs:[di+-643]
xor al,dl
mov gs:[di+-643],al
mov es:[di+-643],al
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_61b61:
mov al,gs:[di+-642]
xor al,dl
mov gs:[di+-642],al
mov es:[di+-642],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_62b61:
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_63b61:
mov al,gs:[di+-641]
xor al,dl
mov gs:[di+-641],al
mov es:[di+-641],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_0b61:
mov al,gs:[di+-640]
xor al,dl
mov gs:[di+-640],al
mov es:[di+-640],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_1b61:
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_2b61:
mov al,gs:[di+-639]
xor al,dl
mov gs:[di+-639],al
mov es:[di+-639],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_3b61:
mov al,gs:[di+-638]
xor al,dl
mov gs:[di+-638],al
mov es:[di+-638],al
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_4b61:
mov al,gs:[di+-637]
xor al,dl
mov gs:[di+-637],al
mov es:[di+-637],al
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_5b61:
mov ax,gs:[di+-637]
xor ax,dx
mov gs:[di+-637],ax
mov es:[di+-637],ax
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_6b61:
mov ax,gs:[di+-636]
xor ax,dx
mov gs:[di+-636],ax
mov es:[di+-636],ax
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_7b61:
mov al,gs:[di+-954]
xor al,dl
mov gs:[di+-954],al
mov es:[di+-954],al
mov ax,gs:[di+-636]
xor ax,dx
mov gs:[di+-636],ax
mov es:[di+-636],ax
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_8b61:
mov al,gs:[di+-953]
xor al,dl
mov gs:[di+-953],al
mov es:[di+-953],al
mov ax,gs:[di+-635]
xor ax,dx
mov gs:[di+-635],ax
mov es:[di+-635],ax
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov al,gs:[di+-316]
xor al,dl
mov gs:[di+-316],al
mov es:[di+-316],al
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_9b61:
mov al,gs:[di+-952]
xor al,dl
mov gs:[di+-952],al
mov es:[di+-952],al
mov ax,gs:[di+-635]
xor ax,dx
mov gs:[di+-635],ax
mov es:[di+-635],ax
mov al,gs:[di+-633]
xor al,dl
mov gs:[di+-633],al
mov es:[di+-633],al
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov al,gs:[di+-316]
xor al,dl
mov gs:[di+-316],al
mov es:[di+-316],al
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_10b61:
mov al,gs:[di+-951]
xor al,dl
mov gs:[di+-951],al
mov es:[di+-951],al
mov ax,gs:[di+-634]
xor ax,dx
mov gs:[di+-634],ax
mov es:[di+-634],ax
mov al,gs:[di+-632]
xor al,dl
mov gs:[di+-632],al
mov es:[di+-632],al
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov ax,gs:[di+-316]
xor ax,dx
mov gs:[di+-316],ax
mov es:[di+-316],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_54b62:
mov ax,gs:[di+-649]
xor ax,dx
mov gs:[di+-649],ax
mov es:[di+-649],ax
mov ax,gs:[di+-327]
xor ax,dx
mov gs:[di+-327],ax
mov es:[di+-327],ax
mov ax,gs:[di+-325]
xor ax,dx
mov gs:[di+-325],ax
mov es:[di+-325],ax
mov al,gs:[di+-323]
xor al,dl
mov gs:[di+-323],al
mov es:[di+-323],al
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_55b62:
mov ax,gs:[di+-648]
xor ax,dx
mov gs:[di+-648],ax
mov es:[di+-648],ax
mov ax,gs:[di+-326]
xor ax,dx
mov gs:[di+-326],ax
mov es:[di+-326],ax
mov ax,gs:[di+-324]
xor ax,dx
mov gs:[di+-324],ax
mov es:[di+-324],ax
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_56b62:
mov al,gs:[di+-647]
xor al,dl
mov gs:[di+-647],al
mov es:[di+-647],al
mov ax,gs:[di+-326]
xor ax,dx
mov gs:[di+-326],ax
mov es:[di+-326],ax
mov ax,gs:[di+-324]
xor ax,dx
mov gs:[di+-324],ax
mov es:[di+-324],ax
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_57b62:
mov al,gs:[di+-646]
xor al,dl
mov gs:[di+-646],al
mov es:[di+-646],al
mov ax,gs:[di+-325]
xor ax,dx
mov gs:[di+-325],ax
mov es:[di+-325],ax
mov ax,gs:[di+-323]
xor ax,dx
mov gs:[di+-323],ax
mov es:[di+-323],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_58b62:
mov al,gs:[di+-645]
xor al,dl
mov gs:[di+-645],al
mov es:[di+-645],al
mov ax,gs:[di+-324]
xor ax,dx
mov gs:[di+-324],ax
mov es:[di+-324],ax
mov al,gs:[di+-322]
xor al,dl
mov gs:[di+-322],al
mov es:[di+-322],al
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_59b62:
mov al,gs:[di+-644]
xor al,dl
mov gs:[di+-644],al
mov es:[di+-644],al
mov ax,gs:[di+-323]
xor ax,dx
mov gs:[di+-323],ax
mov es:[di+-323],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_60b62:
mov ax,gs:[di+-323]
xor ax,dx
mov gs:[di+-323],ax
mov es:[di+-323],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_61b62:
mov ax,gs:[di+-322]
xor ax,dx
mov gs:[di+-322],ax
mov es:[di+-322],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_62b62:
mov al,gs:[di+-321]
xor al,dl
mov gs:[di+-321],al
mov es:[di+-321],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_63b62:
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_0b62:
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_1b62:
mov al,gs:[di+-320]
xor al,dl
mov gs:[di+-320],al
mov es:[di+-320],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_2b62:
mov al,gs:[di+-319]
xor al,dl
mov gs:[di+-319],al
mov es:[di+-319],al
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_3b62:
mov ax,gs:[di+-319]
xor ax,dx
mov gs:[di+-319],ax
mov es:[di+-319],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_4b62:
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_5b62:
mov al,gs:[di+-636]
xor al,dl
mov gs:[di+-636],al
mov es:[di+-636],al
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_6b62:
mov al,gs:[di+-635]
xor al,dl
mov gs:[di+-635],al
mov es:[di+-635],al
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov al,gs:[di+-316]
xor al,dl
mov gs:[di+-316],al
mov es:[di+-316],al
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_7b62:
mov al,gs:[di+-634]
xor al,dl
mov gs:[di+-634],al
mov es:[di+-634],al
mov ax,gs:[di+-318]
xor ax,dx
mov gs:[di+-318],ax
mov es:[di+-318],ax
mov ax,gs:[di+-316]
xor ax,dx
mov gs:[di+-316],ax
mov es:[di+-316],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_8b62:
mov al,gs:[di+-633]
xor al,dl
mov gs:[di+-633],al
mov es:[di+-633],al
mov ax,gs:[di+-317]
xor ax,dx
mov gs:[di+-317],ax
mov es:[di+-317],ax
mov ax,gs:[di+-315]
xor ax,dx
mov gs:[di+-315],ax
mov es:[di+-315],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
ret
lblt_9b62:
mov ax,gs:[di+-633]
xor ax,dx
mov gs:[di+-633],ax
mov es:[di+-633],ax
mov ax,gs:[di+-317]
xor ax,dx
mov gs:[di+-317],ax
mov es:[di+-317],ax
mov ax,gs:[di+-315]
xor ax,dx
mov gs:[di+-315],ax
mov es:[di+-315],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
ret
lblt_10b62:
mov ax,gs:[di+-632]
xor ax,dx
mov gs:[di+-632],ax
mov es:[di+-632],ax
mov ax,gs:[di+-317]
xor ax,dx
mov gs:[di+-317],ax
mov es:[di+-317],ax
mov ax,gs:[di+-315]
xor ax,dx
mov gs:[di+-315],ax
mov es:[di+-315],ax
mov al,gs:[di+-313]
xor al,dl
mov gs:[di+-313],al
mov es:[di+-313],al
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
ret
lblt_54b63:
mov ax,gs:[di+-329]
xor ax,dx
mov gs:[di+-329],ax
mov es:[di+-329],ax
mov ax,gs:[di+-327]
xor ax,dx
mov gs:[di+-327],ax
mov es:[di+-327],ax
mov ax,gs:[di+-5]
xor ax,dx
mov gs:[di+-5],ax
mov es:[di+-5],ax
mov ax,gs:[di+-3]
xor ax,dx
mov gs:[di+-3],ax
mov es:[di+-3],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_55b63:
mov ax,gs:[di+-328]
xor ax,dx
mov gs:[di+-328],ax
mov es:[di+-328],ax
mov ax,gs:[di+-326]
xor ax,dx
mov gs:[di+-326],ax
mov es:[di+-326],ax
mov ax,gs:[di+-4]
xor ax,dx
mov gs:[di+-4],ax
mov es:[di+-4],ax
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_56b63:
mov ax,gs:[di+-327]
xor ax,dx
mov gs:[di+-327],ax
mov es:[di+-327],ax
mov al,gs:[di+-325]
xor al,dl
mov gs:[di+-325],al
mov es:[di+-325],al
mov ax,gs:[di+-4]
xor ax,dx
mov gs:[di+-4],ax
mov es:[di+-4],ax
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_57b63:
mov ax,gs:[di+-326]
xor ax,dx
mov gs:[di+-326],ax
mov es:[di+-326],ax
mov al,gs:[di+-324]
xor al,dl
mov gs:[di+-324],al
mov es:[di+-324],al
mov ax,gs:[di+-3]
xor ax,dx
mov gs:[di+-3],ax
mov es:[di+-3],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_58b63:
mov ax,gs:[di+-325]
xor ax,dx
mov gs:[di+-325],ax
mov es:[di+-325],ax
mov ax,gs:[di+-3]
xor ax,dx
mov gs:[di+-3],ax
mov es:[di+-3],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_59b63:
mov ax,gs:[di+-324]
xor ax,dx
mov gs:[di+-324],ax
mov es:[di+-324],ax
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_60b63:
mov al,gs:[di+-323]
xor al,dl
mov gs:[di+-323],al
mov es:[di+-323],al
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_61b63:
mov al,gs:[di+-322]
xor al,dl
mov gs:[di+-322],al
mov es:[di+-322],al
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_62b63:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_63b63:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_0b63:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_1b63:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_2b63:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_3b63:
mov al,gs:[di+-318]
xor al,dl
mov gs:[di+-318],al
mov es:[di+-318],al
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_4b63:
mov al,gs:[di+-317]
xor al,dl
mov gs:[di+-317],al
mov es:[di+-317],al
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
ret
lblt_5b63:
mov ax,gs:[di+-317]
xor ax,dx
mov gs:[di+-317],ax
mov es:[di+-317],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
ret
lblt_6b63:
mov ax,gs:[di+-316]
xor ax,dx
mov gs:[di+-316],ax
mov es:[di+-316],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
ret
lblt_7b63:
mov ax,gs:[di+-316]
xor ax,dx
mov gs:[di+-316],ax
mov es:[di+-316],ax
mov al,gs:[di+-314]
xor al,dl
mov gs:[di+-314],al
mov es:[di+-314],al
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
ret
lblt_8b63:
mov ax,gs:[di+-315]
xor ax,dx
mov gs:[di+-315],ax
mov es:[di+-315],ax
mov al,gs:[di+-313]
xor al,dl
mov gs:[di+-313],al
mov es:[di+-313],al
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov al,gs:[di+4]
xor al,dl
mov gs:[di+4],al
mov es:[di+4],al
ret
lblt_9b63:
mov ax,gs:[di+-315]
xor ax,dx
mov gs:[di+-315],ax
mov es:[di+-315],ax
mov ax,gs:[di+-313]
xor ax,dx
mov gs:[di+-313],ax
mov es:[di+-313],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov al,gs:[di+4]
xor al,dl
mov gs:[di+4],al
mov es:[di+4],al
ret
lblt_10b63:
mov ax,gs:[di+-314]
xor ax,dx
mov gs:[di+-314],ax
mov es:[di+-314],ax
mov ax,gs:[di+-312]
xor ax,dx
mov gs:[di+-312],ax
mov es:[di+-312],ax
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov ax,gs:[di+4]
xor ax,dx
mov gs:[di+4],ax
mov es:[di+4],ax
ret
lblt_54b0:
mov ax,gs:[di+-9]
xor ax,dx
mov gs:[di+-9],ax
mov es:[di+-9],ax
mov ax,gs:[di+-7]
xor ax,dx
mov gs:[di+-7],ax
mov es:[di+-7],ax
mov ax,gs:[di+-5]
xor ax,dx
mov gs:[di+-5],ax
mov es:[di+-5],ax
mov ax,gs:[di+-3]
xor ax,dx
mov gs:[di+-3],ax
mov es:[di+-3],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_55b0:
mov ax,gs:[di+-8]
xor ax,dx
mov gs:[di+-8],ax
mov es:[di+-8],ax
mov ax,gs:[di+-6]
xor ax,dx
mov gs:[di+-6],ax
mov es:[di+-6],ax
mov ax,gs:[di+-4]
xor ax,dx
mov gs:[di+-4],ax
mov es:[di+-4],ax
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_56b0:
mov ax,gs:[di+-7]
xor ax,dx
mov gs:[di+-7],ax
mov es:[di+-7],ax
mov ax,gs:[di+-5]
xor ax,dx
mov gs:[di+-5],ax
mov es:[di+-5],ax
mov ax,gs:[di+-3]
xor ax,dx
mov gs:[di+-3],ax
mov es:[di+-3],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_57b0:
mov ax,gs:[di+-6]
xor ax,dx
mov gs:[di+-6],ax
mov es:[di+-6],ax
mov ax,gs:[di+-4]
xor ax,dx
mov gs:[di+-4],ax
mov es:[di+-4],ax
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_58b0:
mov ax,gs:[di+-5]
xor ax,dx
mov gs:[di+-5],ax
mov es:[di+-5],ax
mov ax,gs:[di+-3]
xor ax,dx
mov gs:[di+-3],ax
mov es:[di+-3],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_59b0:
mov ax,gs:[di+-4]
xor ax,dx
mov gs:[di+-4],ax
mov es:[di+-4],ax
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_60b0:
mov ax,gs:[di+-3]
xor ax,dx
mov gs:[di+-3],ax
mov es:[di+-3],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_61b0:
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_62b0:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_63b0:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_0b0:
ret
lblt_1b0:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_2b0:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_3b0:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
ret
lblt_4b0:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
ret
lblt_5b0:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov al,gs:[di+4]
xor al,dl
mov gs:[di+4],al
mov es:[di+4],al
ret
lblt_6b0:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov ax,gs:[di+4]
xor ax,dx
mov gs:[di+4],ax
mov es:[di+4],ax
ret
lblt_7b0:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov ax,gs:[di+4]
xor ax,dx
mov gs:[di+4],ax
mov es:[di+4],ax
mov al,gs:[di+6]
xor al,dl
mov gs:[di+6],al
mov es:[di+6],al
ret
lblt_8b0:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov ax,gs:[di+4]
xor ax,dx
mov gs:[di+4],ax
mov es:[di+4],ax
mov ax,gs:[di+6]
xor ax,dx
mov gs:[di+6],ax
mov es:[di+6],ax
ret
lblt_9b0:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov ax,gs:[di+4]
xor ax,dx
mov gs:[di+4],ax
mov es:[di+4],ax
mov ax,gs:[di+6]
xor ax,dx
mov gs:[di+6],ax
mov es:[di+6],ax
mov al,gs:[di+8]
xor al,dl
mov gs:[di+8],al
mov es:[di+8],al
ret
lblt_10b0:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov ax,gs:[di+4]
xor ax,dx
mov gs:[di+4],ax
mov es:[di+4],ax
mov ax,gs:[di+6]
xor ax,dx
mov gs:[di+6],ax
mov es:[di+6],ax
mov ax,gs:[di+8]
xor ax,dx
mov gs:[di+8],ax
mov es:[di+8],ax
ret
lblt_54b1:
mov ax,gs:[di+-5]
xor ax,dx
mov gs:[di+-5],ax
mov es:[di+-5],ax
mov ax,gs:[di+-3]
xor ax,dx
mov gs:[di+-3],ax
mov es:[di+-3],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+311]
xor ax,dx
mov gs:[di+311],ax
mov es:[di+311],ax
mov ax,gs:[di+313]
xor ax,dx
mov gs:[di+313],ax
mov es:[di+313],ax
ret
lblt_55b1:
mov ax,gs:[di+-4]
xor ax,dx
mov gs:[di+-4],ax
mov es:[di+-4],ax
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+312]
xor ax,dx
mov gs:[di+312],ax
mov es:[di+312],ax
mov ax,gs:[di+314]
xor ax,dx
mov gs:[di+314],ax
mov es:[di+314],ax
ret
lblt_56b1:
mov ax,gs:[di+-4]
xor ax,dx
mov gs:[di+-4],ax
mov es:[di+-4],ax
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+313]
xor ax,dx
mov gs:[di+313],ax
mov es:[di+313],ax
mov al,gs:[di+315]
xor al,dl
mov gs:[di+315],al
mov es:[di+315],al
ret
lblt_57b1:
mov ax,gs:[di+-3]
xor ax,dx
mov gs:[di+-3],ax
mov es:[di+-3],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+314]
xor ax,dx
mov gs:[di+314],ax
mov es:[di+314],ax
mov al,gs:[di+316]
xor al,dl
mov gs:[di+316],al
mov es:[di+316],al
ret
lblt_58b1:
mov ax,gs:[di+-3]
xor ax,dx
mov gs:[di+-3],ax
mov es:[di+-3],ax
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+315]
xor ax,dx
mov gs:[di+315],ax
mov es:[di+315],ax
ret
lblt_59b1:
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+316]
xor ax,dx
mov gs:[di+316],ax
mov es:[di+316],ax
ret
lblt_60b1:
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+317]
xor al,dl
mov gs:[di+317],al
mov es:[di+317],al
ret
lblt_61b1:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov al,gs:[di+318]
xor al,dl
mov gs:[di+318],al
mov es:[di+318],al
ret
lblt_62b1:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
ret
lblt_63b1:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_0b1:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_1b1:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
ret
lblt_2b1:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
ret
lblt_3b1:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+322]
xor al,dl
mov gs:[di+322],al
mov es:[di+322],al
ret
lblt_4b1:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
mov al,gs:[di+323]
xor al,dl
mov gs:[di+323],al
mov es:[di+323],al
ret
lblt_5b1:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
mov ax,gs:[di+323]
xor ax,dx
mov gs:[di+323],ax
mov es:[di+323],ax
ret
lblt_6b1:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov ax,gs:[di+324]
xor ax,dx
mov gs:[di+324],ax
mov es:[di+324],ax
ret
lblt_7b1:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov ax,gs:[di+324]
xor ax,dx
mov gs:[di+324],ax
mov es:[di+324],ax
mov al,gs:[di+326]
xor al,dl
mov gs:[di+326],al
mov es:[di+326],al
ret
lblt_8b1:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov al,gs:[di+4]
xor al,dl
mov gs:[di+4],al
mov es:[di+4],al
mov ax,gs:[di+325]
xor ax,dx
mov gs:[di+325],ax
mov es:[di+325],ax
mov al,gs:[di+327]
xor al,dl
mov gs:[di+327],al
mov es:[di+327],al
ret
lblt_9b1:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov al,gs:[di+4]
xor al,dl
mov gs:[di+4],al
mov es:[di+4],al
mov ax,gs:[di+325]
xor ax,dx
mov gs:[di+325],ax
mov es:[di+325],ax
mov ax,gs:[di+327]
xor ax,dx
mov gs:[di+327],ax
mov es:[di+327],ax
ret
lblt_10b1:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+2]
xor ax,dx
mov gs:[di+2],ax
mov es:[di+2],ax
mov ax,gs:[di+4]
xor ax,dx
mov gs:[di+4],ax
mov es:[di+4],ax
mov ax,gs:[di+326]
xor ax,dx
mov gs:[di+326],ax
mov es:[di+326],ax
mov ax,gs:[di+328]
xor ax,dx
mov gs:[di+328],ax
mov es:[di+328],ax
ret
lblt_54b2:
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+313]
xor ax,dx
mov gs:[di+313],ax
mov es:[di+313],ax
mov ax,gs:[di+315]
xor ax,dx
mov gs:[di+315],ax
mov es:[di+315],ax
mov al,gs:[di+317]
xor al,dl
mov gs:[di+317],al
mov es:[di+317],al
mov ax,gs:[di+631]
xor ax,dx
mov gs:[di+631],ax
mov es:[di+631],ax
ret
lblt_55b2:
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+314]
xor ax,dx
mov gs:[di+314],ax
mov es:[di+314],ax
mov ax,gs:[di+316]
xor ax,dx
mov gs:[di+316],ax
mov es:[di+316],ax
mov ax,gs:[di+632]
xor ax,dx
mov gs:[di+632],ax
mov es:[di+632],ax
ret
lblt_56b2:
mov ax,gs:[di+-2]
xor ax,dx
mov gs:[di+-2],ax
mov es:[di+-2],ax
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+314]
xor ax,dx
mov gs:[di+314],ax
mov es:[di+314],ax
mov ax,gs:[di+316]
xor ax,dx
mov gs:[di+316],ax
mov es:[di+316],ax
mov al,gs:[di+633]
xor al,dl
mov gs:[di+633],al
mov es:[di+633],al
ret
lblt_57b2:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+315]
xor ax,dx
mov gs:[di+315],ax
mov es:[di+315],ax
mov ax,gs:[di+317]
xor ax,dx
mov gs:[di+317],ax
mov es:[di+317],ax
mov al,gs:[di+634]
xor al,dl
mov gs:[di+634],al
mov es:[di+634],al
ret
lblt_58b2:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+316]
xor ax,dx
mov gs:[di+316],ax
mov es:[di+316],ax
mov al,gs:[di+318]
xor al,dl
mov gs:[di+318],al
mov es:[di+318],al
mov al,gs:[di+635]
xor al,dl
mov gs:[di+635],al
mov es:[di+635],al
ret
lblt_59b2:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+317]
xor ax,dx
mov gs:[di+317],ax
mov es:[di+317],ax
mov al,gs:[di+636]
xor al,dl
mov gs:[di+636],al
mov es:[di+636],al
ret
lblt_60b2:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+317]
xor ax,dx
mov gs:[di+317],ax
mov es:[di+317],ax
ret
lblt_61b2:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
ret
lblt_62b2:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
ret
lblt_63b2:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
ret
lblt_0b2:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
ret
lblt_1b2:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
ret
lblt_2b2:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
ret
lblt_3b2:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
ret
lblt_4b2:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
ret
lblt_5b2:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov al,gs:[di+644]
xor al,dl
mov gs:[di+644],al
mov es:[di+644],al
ret
lblt_6b2:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov al,gs:[di+324]
xor al,dl
mov gs:[di+324],al
mov es:[di+324],al
mov al,gs:[di+645]
xor al,dl
mov gs:[di+645],al
mov es:[di+645],al
ret
lblt_7b2:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov ax,gs:[di+324]
xor ax,dx
mov gs:[di+324],ax
mov es:[di+324],ax
mov al,gs:[di+646]
xor al,dl
mov gs:[di+646],al
mov es:[di+646],al
ret
lblt_8b2:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
mov ax,gs:[di+323]
xor ax,dx
mov gs:[di+323],ax
mov es:[di+323],ax
mov ax,gs:[di+325]
xor ax,dx
mov gs:[di+325],ax
mov es:[di+325],ax
mov al,gs:[di+647]
xor al,dl
mov gs:[di+647],al
mov es:[di+647],al
ret
lblt_9b2:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
mov ax,gs:[di+323]
xor ax,dx
mov gs:[di+323],ax
mov es:[di+323],ax
mov ax,gs:[di+325]
xor ax,dx
mov gs:[di+325],ax
mov es:[di+325],ax
mov ax,gs:[di+647]
xor ax,dx
mov gs:[di+647],ax
mov es:[di+647],ax
ret
lblt_10b2:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov al,gs:[di+2]
xor al,dl
mov gs:[di+2],al
mov es:[di+2],al
mov ax,gs:[di+323]
xor ax,dx
mov gs:[di+323],ax
mov es:[di+323],ax
mov ax,gs:[di+325]
xor ax,dx
mov gs:[di+325],ax
mov es:[di+325],ax
mov al,gs:[di+327]
xor al,dl
mov gs:[di+327],al
mov es:[di+327],al
mov ax,gs:[di+648]
xor ax,dx
mov gs:[di+648],ax
mov es:[di+648],ax
ret
lblt_54b3:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+315]
xor ax,dx
mov gs:[di+315],ax
mov es:[di+315],ax
mov ax,gs:[di+317]
xor ax,dx
mov gs:[di+317],ax
mov es:[di+317],ax
mov ax,gs:[di+632]
xor ax,dx
mov gs:[di+632],ax
mov es:[di+632],ax
mov al,gs:[di+634]
xor al,dl
mov gs:[di+634],al
mov es:[di+634],al
mov al,gs:[di+951]
xor al,dl
mov gs:[di+951],al
mov es:[di+951],al
ret
lblt_55b3:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+316]
xor ax,dx
mov gs:[di+316],ax
mov es:[di+316],ax
mov al,gs:[di+318]
xor al,dl
mov gs:[di+318],al
mov es:[di+318],al
mov ax,gs:[di+633]
xor ax,dx
mov gs:[di+633],ax
mov es:[di+633],ax
mov al,gs:[di+635]
xor al,dl
mov gs:[di+635],al
mov es:[di+635],al
mov al,gs:[di+952]
xor al,dl
mov gs:[di+952],al
mov es:[di+952],al
ret
lblt_56b3:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+316]
xor ax,dx
mov gs:[di+316],ax
mov es:[di+316],ax
mov al,gs:[di+318]
xor al,dl
mov gs:[di+318],al
mov es:[di+318],al
mov ax,gs:[di+634]
xor ax,dx
mov gs:[di+634],ax
mov es:[di+634],ax
mov al,gs:[di+953]
xor al,dl
mov gs:[di+953],al
mov es:[di+953],al
ret
lblt_57b3:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+317]
xor ax,dx
mov gs:[di+317],ax
mov es:[di+317],ax
mov ax,gs:[di+635]
xor ax,dx
mov gs:[di+635],ax
mov es:[di+635],ax
mov al,gs:[di+954]
xor al,dl
mov gs:[di+954],al
mov es:[di+954],al
ret
lblt_58b3:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+317]
xor ax,dx
mov gs:[di+317],ax
mov es:[di+317],ax
mov ax,gs:[di+635]
xor ax,dx
mov gs:[di+635],ax
mov es:[di+635],ax
ret
lblt_59b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov ax,gs:[di+636]
xor ax,dx
mov gs:[di+636],ax
mov es:[di+636],ax
ret
lblt_60b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov al,gs:[di+637]
xor al,dl
mov gs:[di+637],al
mov es:[di+637],al
ret
lblt_61b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
ret
lblt_62b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
ret
lblt_63b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
ret
lblt_0b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
ret
lblt_1b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
ret
lblt_2b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
ret
lblt_3b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
ret
lblt_4b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov al,gs:[di+643]
xor al,dl
mov gs:[di+643],al
mov es:[di+643],al
ret
lblt_5b3:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov ax,gs:[di+643]
xor ax,dx
mov gs:[di+643],ax
mov es:[di+643],ax
ret
lblt_6b3:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov ax,gs:[di+644]
xor ax,dx
mov gs:[di+644],ax
mov es:[di+644],ax
ret
lblt_7b3:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov ax,gs:[di+644]
xor ax,dx
mov gs:[di+644],ax
mov es:[di+644],ax
mov al,gs:[di+966]
xor al,dl
mov gs:[di+966],al
mov es:[di+966],al
ret
lblt_8b3:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov al,gs:[di+324]
xor al,dl
mov gs:[di+324],al
mov es:[di+324],al
mov ax,gs:[di+645]
xor ax,dx
mov gs:[di+645],ax
mov es:[di+645],ax
mov al,gs:[di+967]
xor al,dl
mov gs:[di+967],al
mov es:[di+967],al
ret
lblt_9b3:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov al,gs:[di+324]
xor al,dl
mov gs:[di+324],al
mov es:[di+324],al
mov ax,gs:[di+645]
xor ax,dx
mov gs:[di+645],ax
mov es:[di+645],ax
mov al,gs:[di+647]
xor al,dl
mov gs:[di+647],al
mov es:[di+647],al
mov al,gs:[di+968]
xor al,dl
mov gs:[di+968],al
mov es:[di+968],al
ret
lblt_10b3:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov ax,gs:[di+324]
xor ax,dx
mov gs:[di+324],ax
mov es:[di+324],ax
mov ax,gs:[di+646]
xor ax,dx
mov gs:[di+646],ax
mov es:[di+646],ax
mov al,gs:[di+648]
xor al,dl
mov gs:[di+648],al
mov es:[di+648],al
mov al,gs:[di+969]
xor al,dl
mov gs:[di+969],al
mov es:[di+969],al
ret
lblt_54b4:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+317]
xor ax,dx
mov gs:[di+317],ax
mov es:[di+317],ax
mov ax,gs:[di+634]
xor ax,dx
mov gs:[di+634],ax
mov es:[di+634],ax
mov al,gs:[di+636]
xor al,dl
mov gs:[di+636],al
mov es:[di+636],al
mov ax,gs:[di+952]
xor ax,dx
mov gs:[di+952],ax
mov es:[di+952],ax
mov al,gs:[di+1271]
xor al,dl
mov gs:[di+1271],al
mov es:[di+1271],al
ret
lblt_55b4:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+317]
xor ax,dx
mov gs:[di+317],ax
mov es:[di+317],ax
mov ax,gs:[di+635]
xor ax,dx
mov gs:[di+635],ax
mov es:[di+635],ax
mov ax,gs:[di+953]
xor ax,dx
mov gs:[di+953],ax
mov es:[di+953],ax
mov al,gs:[di+1272]
xor al,dl
mov gs:[di+1272],al
mov es:[di+1272],al
ret
lblt_56b4:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+317]
xor ax,dx
mov gs:[di+317],ax
mov es:[di+317],ax
mov ax,gs:[di+635]
xor ax,dx
mov gs:[di+635],ax
mov es:[di+635],ax
mov ax,gs:[di+953]
xor ax,dx
mov gs:[di+953],ax
mov es:[di+953],ax
ret
lblt_57b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov ax,gs:[di+636]
xor ax,dx
mov gs:[di+636],ax
mov es:[di+636],ax
mov ax,gs:[di+954]
xor ax,dx
mov gs:[di+954],ax
mov es:[di+954],ax
ret
lblt_58b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov al,gs:[di+637]
xor al,dl
mov gs:[di+637],al
mov es:[di+637],al
mov ax,gs:[di+955]
xor ax,dx
mov gs:[di+955],ax
mov es:[di+955],ax
ret
lblt_59b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov ax,gs:[di+637]
xor ax,dx
mov gs:[di+637],ax
mov es:[di+637],ax
mov al,gs:[di+956]
xor al,dl
mov gs:[di+956],al
mov es:[di+956],al
ret
lblt_60b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov al,gs:[di+957]
xor al,dl
mov gs:[di+957],al
mov es:[di+957],al
ret
lblt_61b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+958]
xor al,dl
mov gs:[di+958],al
mov es:[di+958],al
ret
lblt_62b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
ret
lblt_63b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
ret
lblt_0b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
ret
lblt_1b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
ret
lblt_2b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
ret
lblt_3b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+962]
xor al,dl
mov gs:[di+962],al
mov es:[di+962],al
ret
lblt_4b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov al,gs:[di+963]
xor al,dl
mov gs:[di+963],al
mov es:[di+963],al
ret
lblt_5b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov ax,gs:[di+642]
xor ax,dx
mov gs:[di+642],ax
mov es:[di+642],ax
mov al,gs:[di+964]
xor al,dl
mov gs:[di+964],al
mov es:[di+964],al
ret
lblt_6b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov al,gs:[di+643]
xor al,dl
mov gs:[di+643],al
mov es:[di+643],al
mov ax,gs:[di+964]
xor ax,dx
mov gs:[di+964],ax
mov es:[di+964],ax
ret
lblt_7b4:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov ax,gs:[di+643]
xor ax,dx
mov gs:[di+643],ax
mov es:[di+643],ax
mov ax,gs:[di+965]
xor ax,dx
mov gs:[di+965],ax
mov es:[di+965],ax
ret
lblt_8b4:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov ax,gs:[di+644]
xor ax,dx
mov gs:[di+644],ax
mov es:[di+644],ax
mov ax,gs:[di+966]
xor ax,dx
mov gs:[di+966],ax
mov es:[di+966],ax
ret
lblt_9b4:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov ax,gs:[di+644]
xor ax,dx
mov gs:[di+644],ax
mov es:[di+644],ax
mov ax,gs:[di+966]
xor ax,dx
mov gs:[di+966],ax
mov es:[di+966],ax
mov al,gs:[di+1288]
xor al,dl
mov gs:[di+1288],al
mov es:[di+1288],al
ret
lblt_10b4:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov ax,gs:[di+644]
xor ax,dx
mov gs:[di+644],ax
mov es:[di+644],ax
mov al,gs:[di+646]
xor al,dl
mov gs:[di+646],al
mov es:[di+646],al
mov ax,gs:[di+967]
xor ax,dx
mov gs:[di+967],ax
mov es:[di+967],ax
mov al,gs:[di+1289]
xor al,dl
mov gs:[di+1289],al
mov es:[di+1289],al
ret
lblt_54b5:
mov ax,gs:[di+-1]
xor ax,dx
mov gs:[di+-1],ax
mov es:[di+-1],ax
mov ax,gs:[di+317]
xor ax,dx
mov gs:[di+317],ax
mov es:[di+317],ax
mov ax,gs:[di+635]
xor ax,dx
mov gs:[di+635],ax
mov es:[di+635],ax
mov ax,gs:[di+953]
xor ax,dx
mov gs:[di+953],ax
mov es:[di+953],ax
mov ax,gs:[di+1271]
xor ax,dx
mov gs:[di+1271],ax
mov es:[di+1271],ax
ret
lblt_55b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov ax,gs:[di+636]
xor ax,dx
mov gs:[di+636],ax
mov es:[di+636],ax
mov ax,gs:[di+954]
xor ax,dx
mov gs:[di+954],ax
mov es:[di+954],ax
mov ax,gs:[di+1272]
xor ax,dx
mov gs:[di+1272],ax
mov es:[di+1272],ax
ret
lblt_56b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov ax,gs:[di+636]
xor ax,dx
mov gs:[di+636],ax
mov es:[di+636],ax
mov al,gs:[di+955]
xor al,dl
mov gs:[di+955],al
mov es:[di+955],al
mov ax,gs:[di+1273]
xor ax,dx
mov gs:[di+1273],ax
mov es:[di+1273],ax
ret
lblt_57b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov al,gs:[di+637]
xor al,dl
mov gs:[di+637],al
mov es:[di+637],al
mov al,gs:[di+956]
xor al,dl
mov gs:[di+956],al
mov es:[di+956],al
mov ax,gs:[di+1274]
xor ax,dx
mov gs:[di+1274],ax
mov es:[di+1274],ax
ret
lblt_58b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov ax,gs:[di+637]
xor ax,dx
mov gs:[di+637],ax
mov es:[di+637],ax
mov al,gs:[di+956]
xor al,dl
mov gs:[di+956],al
mov es:[di+956],al
mov al,gs:[di+1275]
xor al,dl
mov gs:[di+1275],al
mov es:[di+1275],al
ret
lblt_59b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov al,gs:[di+957]
xor al,dl
mov gs:[di+957],al
mov es:[di+957],al
mov al,gs:[di+1276]
xor al,dl
mov gs:[di+1276],al
mov es:[di+1276],al
ret
lblt_60b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov al,gs:[di+958]
xor al,dl
mov gs:[di+958],al
mov es:[di+958],al
mov al,gs:[di+1277]
xor al,dl
mov gs:[di+1277],al
mov es:[di+1277],al
ret
lblt_61b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+958]
xor al,dl
mov gs:[di+958],al
mov es:[di+958],al
mov al,gs:[di+1278]
xor al,dl
mov gs:[di+1278],al
mov es:[di+1278],al
ret
lblt_62b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
mov al,gs:[di+1278]
xor al,dl
mov gs:[di+1278],al
mov es:[di+1278],al
ret
lblt_63b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
mov al,gs:[di+1279]
xor al,dl
mov gs:[di+1279],al
mov es:[di+1279],al
ret
lblt_0b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
mov al,gs:[di+1280]
xor al,dl
mov gs:[di+1280],al
mov es:[di+1280],al
ret
lblt_1b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
mov al,gs:[di+1281]
xor al,dl
mov gs:[di+1281],al
mov es:[di+1281],al
ret
lblt_2b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
mov al,gs:[di+1282]
xor al,dl
mov gs:[di+1282],al
mov es:[di+1282],al
ret
lblt_3b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+962]
xor al,dl
mov gs:[di+962],al
mov es:[di+962],al
mov al,gs:[di+1282]
xor al,dl
mov gs:[di+1282],al
mov es:[di+1282],al
ret
lblt_4b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov al,gs:[di+962]
xor al,dl
mov gs:[di+962],al
mov es:[di+962],al
mov al,gs:[di+1283]
xor al,dl
mov gs:[di+1283],al
mov es:[di+1283],al
ret
lblt_5b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov al,gs:[di+963]
xor al,dl
mov gs:[di+963],al
mov es:[di+963],al
mov al,gs:[di+1284]
xor al,dl
mov gs:[di+1284],al
mov es:[di+1284],al
ret
lblt_6b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov ax,gs:[di+642]
xor ax,dx
mov gs:[di+642],ax
mov es:[di+642],ax
mov al,gs:[di+964]
xor al,dl
mov gs:[di+964],al
mov es:[di+964],al
mov al,gs:[di+1285]
xor al,dl
mov gs:[di+1285],al
mov es:[di+1285],al
ret
lblt_7b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov al,gs:[di+643]
xor al,dl
mov gs:[di+643],al
mov es:[di+643],al
mov al,gs:[di+964]
xor al,dl
mov gs:[di+964],al
mov es:[di+964],al
mov ax,gs:[di+1285]
xor ax,dx
mov gs:[di+1285],ax
mov es:[di+1285],ax
ret
lblt_8b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov ax,gs:[di+643]
xor ax,dx
mov gs:[di+643],ax
mov es:[di+643],ax
mov al,gs:[di+965]
xor al,dl
mov gs:[di+965],al
mov es:[di+965],al
mov ax,gs:[di+1286]
xor ax,dx
mov gs:[di+1286],ax
mov es:[di+1286],ax
ret
lblt_9b5:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov ax,gs:[di+643]
xor ax,dx
mov gs:[di+643],ax
mov es:[di+643],ax
mov ax,gs:[di+965]
xor ax,dx
mov gs:[di+965],ax
mov es:[di+965],ax
mov ax,gs:[di+1287]
xor ax,dx
mov gs:[di+1287],ax
mov es:[di+1287],ax
ret
lblt_10b5:
mov ax,gs:[di+0]
xor ax,dx
mov gs:[di+0],ax
mov es:[di+0],ax
mov ax,gs:[di+322]
xor ax,dx
mov gs:[di+322],ax
mov es:[di+322],ax
mov ax,gs:[di+644]
xor ax,dx
mov gs:[di+644],ax
mov es:[di+644],ax
mov ax,gs:[di+966]
xor ax,dx
mov gs:[di+966],ax
mov es:[di+966],ax
mov ax,gs:[di+1288]
xor ax,dx
mov gs:[di+1288],ax
mov es:[di+1288],ax
ret
lblt_54b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov ax,gs:[di+636]
xor ax,dx
mov gs:[di+636],ax
mov es:[di+636],ax
mov al,gs:[di+955]
xor al,dl
mov gs:[di+955],al
mov es:[di+955],al
mov ax,gs:[di+1273]
xor ax,dx
mov gs:[di+1273],ax
mov es:[di+1273],ax
mov ax,gs:[di+1591]
xor ax,dx
mov gs:[di+1591],ax
mov es:[di+1591],ax
ret
lblt_55b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov al,gs:[di+637]
xor al,dl
mov gs:[di+637],al
mov es:[di+637],al
mov ax,gs:[di+955]
xor ax,dx
mov gs:[di+955],ax
mov es:[di+955],ax
mov al,gs:[di+1274]
xor al,dl
mov gs:[di+1274],al
mov es:[di+1274],al
mov ax,gs:[di+1592]
xor ax,dx
mov gs:[di+1592],ax
mov es:[di+1592],ax
ret
lblt_56b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov al,gs:[di+637]
xor al,dl
mov gs:[di+637],al
mov es:[di+637],al
mov al,gs:[di+956]
xor al,dl
mov gs:[di+956],al
mov es:[di+956],al
mov ax,gs:[di+1274]
xor ax,dx
mov gs:[di+1274],ax
mov es:[di+1274],ax
mov al,gs:[di+1593]
xor al,dl
mov gs:[di+1593],al
mov es:[di+1593],al
ret
lblt_57b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov ax,gs:[di+956]
xor ax,dx
mov gs:[di+956],ax
mov es:[di+956],ax
mov al,gs:[di+1275]
xor al,dl
mov gs:[di+1275],al
mov es:[di+1275],al
mov al,gs:[di+1594]
xor al,dl
mov gs:[di+1594],al
mov es:[di+1594],al
ret
lblt_58b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov al,gs:[di+957]
xor al,dl
mov gs:[di+957],al
mov es:[di+957],al
mov al,gs:[di+1276]
xor al,dl
mov gs:[di+1276],al
mov es:[di+1276],al
mov al,gs:[di+1595]
xor al,dl
mov gs:[di+1595],al
mov es:[di+1595],al
ret
lblt_59b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov al,gs:[di+958]
xor al,dl
mov gs:[di+958],al
mov es:[di+958],al
mov al,gs:[di+1277]
xor al,dl
mov gs:[di+1277],al
mov es:[di+1277],al
mov al,gs:[di+1596]
xor al,dl
mov gs:[di+1596],al
mov es:[di+1596],al
ret
lblt_60b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+958]
xor al,dl
mov gs:[di+958],al
mov es:[di+958],al
mov al,gs:[di+1277]
xor al,dl
mov gs:[di+1277],al
mov es:[di+1277],al
mov al,gs:[di+1597]
xor al,dl
mov gs:[di+1597],al
mov es:[di+1597],al
ret
lblt_61b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
mov al,gs:[di+1278]
xor al,dl
mov gs:[di+1278],al
mov es:[di+1278],al
mov al,gs:[di+1598]
xor al,dl
mov gs:[di+1598],al
mov es:[di+1598],al
ret
lblt_62b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
mov al,gs:[di+1279]
xor al,dl
mov gs:[di+1279],al
mov es:[di+1279],al
mov al,gs:[di+1598]
xor al,dl
mov gs:[di+1598],al
mov es:[di+1598],al
ret
lblt_63b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
mov al,gs:[di+1279]
xor al,dl
mov gs:[di+1279],al
mov es:[di+1279],al
mov al,gs:[di+1599]
xor al,dl
mov gs:[di+1599],al
mov es:[di+1599],al
ret
lblt_0b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
mov al,gs:[di+1280]
xor al,dl
mov gs:[di+1280],al
mov es:[di+1280],al
mov al,gs:[di+1600]
xor al,dl
mov gs:[di+1600],al
mov es:[di+1600],al
ret
lblt_1b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
mov al,gs:[di+1281]
xor al,dl
mov gs:[di+1281],al
mov es:[di+1281],al
mov al,gs:[di+1601]
xor al,dl
mov gs:[di+1601],al
mov es:[di+1601],al
ret
lblt_2b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
mov al,gs:[di+1281]
xor al,dl
mov gs:[di+1281],al
mov es:[di+1281],al
mov al,gs:[di+1602]
xor al,dl
mov gs:[di+1602],al
mov es:[di+1602],al
ret
lblt_3b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
mov al,gs:[di+1282]
xor al,dl
mov gs:[di+1282],al
mov es:[di+1282],al
mov al,gs:[di+1602]
xor al,dl
mov gs:[di+1602],al
mov es:[di+1602],al
ret
lblt_4b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+962]
xor al,dl
mov gs:[di+962],al
mov es:[di+962],al
mov al,gs:[di+1283]
xor al,dl
mov gs:[di+1283],al
mov es:[di+1283],al
mov al,gs:[di+1603]
xor al,dl
mov gs:[di+1603],al
mov es:[di+1603],al
ret
lblt_5b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov al,gs:[di+962]
xor al,dl
mov gs:[di+962],al
mov es:[di+962],al
mov al,gs:[di+1283]
xor al,dl
mov gs:[di+1283],al
mov es:[di+1283],al
mov al,gs:[di+1604]
xor al,dl
mov gs:[di+1604],al
mov es:[di+1604],al
ret
lblt_6b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov al,gs:[di+963]
xor al,dl
mov gs:[di+963],al
mov es:[di+963],al
mov al,gs:[di+1284]
xor al,dl
mov gs:[di+1284],al
mov es:[di+1284],al
mov al,gs:[di+1605]
xor al,dl
mov gs:[di+1605],al
mov es:[di+1605],al
ret
lblt_7b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov ax,gs:[di+963]
xor ax,dx
mov gs:[di+963],ax
mov es:[di+963],ax
mov al,gs:[di+1285]
xor al,dl
mov gs:[di+1285],al
mov es:[di+1285],al
mov al,gs:[di+1606]
xor al,dl
mov gs:[di+1606],al
mov es:[di+1606],al
ret
lblt_8b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov al,gs:[di+643]
xor al,dl
mov gs:[di+643],al
mov es:[di+643],al
mov al,gs:[di+964]
xor al,dl
mov gs:[di+964],al
mov es:[di+964],al
mov ax,gs:[di+1285]
xor ax,dx
mov gs:[di+1285],ax
mov es:[di+1285],ax
mov al,gs:[di+1607]
xor al,dl
mov gs:[di+1607],al
mov es:[di+1607],al
ret
lblt_9b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov al,gs:[di+643]
xor al,dl
mov gs:[di+643],al
mov es:[di+643],al
mov ax,gs:[di+964]
xor ax,dx
mov gs:[di+964],ax
mov es:[di+964],ax
mov al,gs:[di+1286]
xor al,dl
mov gs:[di+1286],al
mov es:[di+1286],al
mov ax,gs:[di+1607]
xor ax,dx
mov gs:[di+1607],ax
mov es:[di+1607],ax
ret
lblt_10b6:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov ax,gs:[di+643]
xor ax,dx
mov gs:[di+643],ax
mov es:[di+643],ax
mov al,gs:[di+965]
xor al,dl
mov gs:[di+965],al
mov es:[di+965],al
mov ax,gs:[di+1286]
xor ax,dx
mov gs:[di+1286],ax
mov es:[di+1286],ax
mov ax,gs:[di+1608]
xor ax,dx
mov gs:[di+1608],ax
mov es:[di+1608],ax
ret
lblt_54b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+318]
xor ax,dx
mov gs:[di+318],ax
mov es:[di+318],ax
mov al,gs:[di+637]
xor al,dl
mov gs:[di+637],al
mov es:[di+637],al
mov ax,gs:[di+955]
xor ax,dx
mov gs:[di+955],ax
mov es:[di+955],ax
mov al,gs:[di+1274]
xor al,dl
mov gs:[di+1274],al
mov es:[di+1274],al
mov al,gs:[di+1593]
xor al,dl
mov gs:[di+1593],al
mov es:[di+1593],al
mov ax,gs:[di+1911]
xor ax,dx
mov gs:[di+1911],ax
mov es:[di+1911],ax
ret
lblt_55b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov ax,gs:[di+637]
xor ax,dx
mov gs:[di+637],ax
mov es:[di+637],ax
mov al,gs:[di+956]
xor al,dl
mov gs:[di+956],al
mov es:[di+956],al
mov al,gs:[di+1275]
xor al,dl
mov gs:[di+1275],al
mov es:[di+1275],al
mov ax,gs:[di+1593]
xor ax,dx
mov gs:[di+1593],ax
mov es:[di+1593],ax
mov al,gs:[di+1912]
xor al,dl
mov gs:[di+1912],al
mov es:[di+1912],al
ret
lblt_56b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov ax,gs:[di+956]
xor ax,dx
mov gs:[di+956],ax
mov es:[di+956],ax
mov al,gs:[di+1275]
xor al,dl
mov gs:[di+1275],al
mov es:[di+1275],al
mov al,gs:[di+1594]
xor al,dl
mov gs:[di+1594],al
mov es:[di+1594],al
mov al,gs:[di+1913]
xor al,dl
mov gs:[di+1913],al
mov es:[di+1913],al
ret
lblt_57b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov al,gs:[di+957]
xor al,dl
mov gs:[di+957],al
mov es:[di+957],al
mov al,gs:[di+1276]
xor al,dl
mov gs:[di+1276],al
mov es:[di+1276],al
mov al,gs:[di+1595]
xor al,dl
mov gs:[di+1595],al
mov es:[di+1595],al
mov al,gs:[di+1914]
xor al,dl
mov gs:[di+1914],al
mov es:[di+1914],al
ret
lblt_58b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov al,gs:[di+957]
xor al,dl
mov gs:[di+957],al
mov es:[di+957],al
mov al,gs:[di+1277]
xor al,dl
mov gs:[di+1277],al
mov es:[di+1277],al
mov al,gs:[di+1596]
xor al,dl
mov gs:[di+1596],al
mov es:[di+1596],al
mov al,gs:[di+1915]
xor al,dl
mov gs:[di+1915],al
mov es:[di+1915],al
ret
lblt_59b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+958]
xor al,dl
mov gs:[di+958],al
mov es:[di+958],al
mov al,gs:[di+1277]
xor al,dl
mov gs:[di+1277],al
mov es:[di+1277],al
mov al,gs:[di+1596]
xor al,dl
mov gs:[di+1596],al
mov es:[di+1596],al
mov al,gs:[di+1916]
xor al,dl
mov gs:[di+1916],al
mov es:[di+1916],al
ret
lblt_60b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+958]
xor al,dl
mov gs:[di+958],al
mov es:[di+958],al
mov al,gs:[di+1278]
xor al,dl
mov gs:[di+1278],al
mov es:[di+1278],al
mov al,gs:[di+1597]
xor al,dl
mov gs:[di+1597],al
mov es:[di+1597],al
mov al,gs:[di+1917]
xor al,dl
mov gs:[di+1917],al
mov es:[di+1917],al
ret
lblt_61b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
mov al,gs:[di+1278]
xor al,dl
mov gs:[di+1278],al
mov es:[di+1278],al
mov al,gs:[di+1598]
xor al,dl
mov gs:[di+1598],al
mov es:[di+1598],al
mov al,gs:[di+1917]
xor al,dl
mov gs:[di+1917],al
mov es:[di+1917],al
ret
lblt_62b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
mov al,gs:[di+1279]
xor al,dl
mov gs:[di+1279],al
mov es:[di+1279],al
mov al,gs:[di+1599]
xor al,dl
mov gs:[di+1599],al
mov es:[di+1599],al
mov al,gs:[di+1918]
xor al,dl
mov gs:[di+1918],al
mov es:[di+1918],al
ret
lblt_63b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
mov al,gs:[di+1279]
xor al,dl
mov gs:[di+1279],al
mov es:[di+1279],al
mov al,gs:[di+1599]
xor al,dl
mov gs:[di+1599],al
mov es:[di+1599],al
mov al,gs:[di+1919]
xor al,dl
mov gs:[di+1919],al
mov es:[di+1919],al
ret
lblt_0b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
mov al,gs:[di+1280]
xor al,dl
mov gs:[di+1280],al
mov es:[di+1280],al
mov al,gs:[di+1600]
xor al,dl
mov gs:[di+1600],al
mov es:[di+1600],al
mov al,gs:[di+1920]
xor al,dl
mov gs:[di+1920],al
mov es:[di+1920],al
ret
lblt_1b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
mov al,gs:[di+1281]
xor al,dl
mov gs:[di+1281],al
mov es:[di+1281],al
mov al,gs:[di+1601]
xor al,dl
mov gs:[di+1601],al
mov es:[di+1601],al
mov al,gs:[di+1921]
xor al,dl
mov gs:[di+1921],al
mov es:[di+1921],al
ret
lblt_2b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
mov al,gs:[di+1281]
xor al,dl
mov gs:[di+1281],al
mov es:[di+1281],al
mov al,gs:[di+1601]
xor al,dl
mov gs:[di+1601],al
mov es:[di+1601],al
mov al,gs:[di+1922]
xor al,dl
mov gs:[di+1922],al
mov es:[di+1922],al
ret
lblt_3b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
mov al,gs:[di+1282]
xor al,dl
mov gs:[di+1282],al
mov es:[di+1282],al
mov al,gs:[di+1602]
xor al,dl
mov gs:[di+1602],al
mov es:[di+1602],al
mov al,gs:[di+1923]
xor al,dl
mov gs:[di+1923],al
mov es:[di+1923],al
ret
lblt_4b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+962]
xor al,dl
mov gs:[di+962],al
mov es:[di+962],al
mov al,gs:[di+1282]
xor al,dl
mov gs:[di+1282],al
mov es:[di+1282],al
mov al,gs:[di+1603]
xor al,dl
mov gs:[di+1603],al
mov es:[di+1603],al
mov al,gs:[di+1923]
xor al,dl
mov gs:[di+1923],al
mov es:[di+1923],al
ret
lblt_5b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+962]
xor al,dl
mov gs:[di+962],al
mov es:[di+962],al
mov al,gs:[di+1283]
xor al,dl
mov gs:[di+1283],al
mov es:[di+1283],al
mov al,gs:[di+1604]
xor al,dl
mov gs:[di+1604],al
mov es:[di+1604],al
mov al,gs:[di+1924]
xor al,dl
mov gs:[di+1924],al
mov es:[di+1924],al
ret
lblt_6b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov al,gs:[di+963]
xor al,dl
mov gs:[di+963],al
mov es:[di+963],al
mov al,gs:[di+1283]
xor al,dl
mov gs:[di+1283],al
mov es:[di+1283],al
mov al,gs:[di+1604]
xor al,dl
mov gs:[di+1604],al
mov es:[di+1604],al
mov al,gs:[di+1925]
xor al,dl
mov gs:[di+1925],al
mov es:[di+1925],al
ret
lblt_7b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov al,gs:[di+963]
xor al,dl
mov gs:[di+963],al
mov es:[di+963],al
mov al,gs:[di+1284]
xor al,dl
mov gs:[di+1284],al
mov es:[di+1284],al
mov al,gs:[di+1605]
xor al,dl
mov gs:[di+1605],al
mov es:[di+1605],al
mov al,gs:[di+1926]
xor al,dl
mov gs:[di+1926],al
mov es:[di+1926],al
ret
lblt_8b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov ax,gs:[di+963]
xor ax,dx
mov gs:[di+963],ax
mov es:[di+963],ax
mov al,gs:[di+1285]
xor al,dl
mov gs:[di+1285],al
mov es:[di+1285],al
mov al,gs:[di+1606]
xor al,dl
mov gs:[di+1606],al
mov es:[di+1606],al
mov al,gs:[di+1927]
xor al,dl
mov gs:[di+1927],al
mov es:[di+1927],al
ret
lblt_9b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov ax,gs:[di+642]
xor ax,dx
mov gs:[di+642],ax
mov es:[di+642],ax
mov al,gs:[di+964]
xor al,dl
mov gs:[di+964],al
mov es:[di+964],al
mov al,gs:[di+1285]
xor al,dl
mov gs:[di+1285],al
mov es:[di+1285],al
mov ax,gs:[di+1606]
xor ax,dx
mov gs:[di+1606],ax
mov es:[di+1606],ax
mov al,gs:[di+1928]
xor al,dl
mov gs:[di+1928],al
mov es:[di+1928],al
ret
lblt_10b7:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov ax,gs:[di+321]
xor ax,dx
mov gs:[di+321],ax
mov es:[di+321],ax
mov al,gs:[di+643]
xor al,dl
mov gs:[di+643],al
mov es:[di+643],al
mov ax,gs:[di+964]
xor ax,dx
mov gs:[di+964],ax
mov es:[di+964],ax
mov al,gs:[di+1286]
xor al,dl
mov gs:[di+1286],al
mov es:[di+1286],al
mov al,gs:[di+1607]
xor al,dl
mov gs:[di+1607],al
mov es:[di+1607],al
mov ax,gs:[di+1928]
xor ax,dx
mov gs:[di+1928],ax
mov es:[di+1928],ax
ret
lblt_54b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov ax,gs:[di+637]
xor ax,dx
mov gs:[di+637],ax
mov es:[di+637],ax
mov al,gs:[di+956]
xor al,dl
mov gs:[di+956],al
mov es:[di+956],al
mov al,gs:[di+1275]
xor al,dl
mov gs:[di+1275],al
mov es:[di+1275],al
mov al,gs:[di+1594]
xor al,dl
mov gs:[di+1594],al
mov es:[di+1594],al
mov ax,gs:[di+1912]
xor ax,dx
mov gs:[di+1912],ax
mov es:[di+1912],ax
mov al,gs:[di+2231]
xor al,dl
mov gs:[di+2231],al
mov es:[di+2231],al
ret
lblt_55b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov al,gs:[di+957]
xor al,dl
mov gs:[di+957],al
mov es:[di+957],al
mov ax,gs:[di+1275]
xor ax,dx
mov gs:[di+1275],ax
mov es:[di+1275],ax
mov al,gs:[di+1594]
xor al,dl
mov gs:[di+1594],al
mov es:[di+1594],al
mov al,gs:[di+1913]
xor al,dl
mov gs:[di+1913],al
mov es:[di+1913],al
mov al,gs:[di+2232]
xor al,dl
mov gs:[di+2232],al
mov es:[di+2232],al
ret
lblt_56b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov al,gs:[di+957]
xor al,dl
mov gs:[di+957],al
mov es:[di+957],al
mov al,gs:[di+1276]
xor al,dl
mov gs:[di+1276],al
mov es:[di+1276],al
mov al,gs:[di+1595]
xor al,dl
mov gs:[di+1595],al
mov es:[di+1595],al
mov al,gs:[di+1914]
xor al,dl
mov gs:[di+1914],al
mov es:[di+1914],al
mov al,gs:[di+2233]
xor al,dl
mov gs:[di+2233],al
mov es:[di+2233],al
ret
lblt_57b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+638]
xor al,dl
mov gs:[di+638],al
mov es:[di+638],al
mov al,gs:[di+957]
xor al,dl
mov gs:[di+957],al
mov es:[di+957],al
mov al,gs:[di+1277]
xor al,dl
mov gs:[di+1277],al
mov es:[di+1277],al
mov al,gs:[di+1596]
xor al,dl
mov gs:[di+1596],al
mov es:[di+1596],al
mov al,gs:[di+1915]
xor al,dl
mov gs:[di+1915],al
mov es:[di+1915],al
mov al,gs:[di+2234]
xor al,dl
mov gs:[di+2234],al
mov es:[di+2234],al
ret
lblt_58b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+958]
xor al,dl
mov gs:[di+958],al
mov es:[di+958],al
mov al,gs:[di+1277]
xor al,dl
mov gs:[di+1277],al
mov es:[di+1277],al
mov al,gs:[di+1596]
xor al,dl
mov gs:[di+1596],al
mov es:[di+1596],al
mov al,gs:[di+1916]
xor al,dl
mov gs:[di+1916],al
mov es:[di+1916],al
mov al,gs:[di+2235]
xor al,dl
mov gs:[di+2235],al
mov es:[di+2235],al
ret
lblt_59b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+319]
xor al,dl
mov gs:[di+319],al
mov es:[di+319],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+958]
xor al,dl
mov gs:[di+958],al
mov es:[di+958],al
mov al,gs:[di+1278]
xor al,dl
mov gs:[di+1278],al
mov es:[di+1278],al
mov al,gs:[di+1597]
xor al,dl
mov gs:[di+1597],al
mov es:[di+1597],al
mov al,gs:[di+1916]
xor al,dl
mov gs:[di+1916],al
mov es:[di+1916],al
mov al,gs:[di+2236]
xor al,dl
mov gs:[di+2236],al
mov es:[di+2236],al
ret
lblt_60b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
mov al,gs:[di+1278]
xor al,dl
mov gs:[di+1278],al
mov es:[di+1278],al
mov al,gs:[di+1598]
xor al,dl
mov gs:[di+1598],al
mov es:[di+1598],al
mov al,gs:[di+1917]
xor al,dl
mov gs:[di+1917],al
mov es:[di+1917],al
mov al,gs:[di+2237]
xor al,dl
mov gs:[di+2237],al
mov es:[di+2237],al
ret
lblt_61b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+639]
xor al,dl
mov gs:[di+639],al
mov es:[di+639],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
mov al,gs:[di+1279]
xor al,dl
mov gs:[di+1279],al
mov es:[di+1279],al
mov al,gs:[di+1598]
xor al,dl
mov gs:[di+1598],al
mov es:[di+1598],al
mov al,gs:[di+1918]
xor al,dl
mov gs:[di+1918],al
mov es:[di+1918],al
mov al,gs:[di+2237]
xor al,dl
mov gs:[di+2237],al
mov es:[di+2237],al
ret
lblt_62b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+959]
xor al,dl
mov gs:[di+959],al
mov es:[di+959],al
mov al,gs:[di+1279]
xor al,dl
mov gs:[di+1279],al
mov es:[di+1279],al
mov al,gs:[di+1599]
xor al,dl
mov gs:[di+1599],al
mov es:[di+1599],al
mov al,gs:[di+1919]
xor al,dl
mov gs:[di+1919],al
mov es:[di+1919],al
mov al,gs:[di+2238]
xor al,dl
mov gs:[di+2238],al
mov es:[di+2238],al
ret
lblt_63b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
mov al,gs:[di+1280]
xor al,dl
mov gs:[di+1280],al
mov es:[di+1280],al
mov al,gs:[di+1599]
xor al,dl
mov gs:[di+1599],al
mov es:[di+1599],al
mov al,gs:[di+1919]
xor al,dl
mov gs:[di+1919],al
mov es:[di+1919],al
mov al,gs:[di+2239]
xor al,dl
mov gs:[di+2239],al
mov es:[di+2239],al
ret
lblt_0b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
mov al,gs:[di+1280]
xor al,dl
mov gs:[di+1280],al
mov es:[di+1280],al
mov al,gs:[di+1600]
xor al,dl
mov gs:[di+1600],al
mov es:[di+1600],al
mov al,gs:[di+1920]
xor al,dl
mov gs:[di+1920],al
mov es:[di+1920],al
mov al,gs:[di+2240]
xor al,dl
mov gs:[di+2240],al
mov es:[di+2240],al
ret
lblt_1b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+960]
xor al,dl
mov gs:[di+960],al
mov es:[di+960],al
mov al,gs:[di+1280]
xor al,dl
mov gs:[di+1280],al
mov es:[di+1280],al
mov al,gs:[di+1601]
xor al,dl
mov gs:[di+1601],al
mov es:[di+1601],al
mov al,gs:[di+1921]
xor al,dl
mov gs:[di+1921],al
mov es:[di+1921],al
mov al,gs:[di+2241]
xor al,dl
mov gs:[di+2241],al
mov es:[di+2241],al
ret
lblt_2b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+640]
xor al,dl
mov gs:[di+640],al
mov es:[di+640],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
mov al,gs:[di+1281]
xor al,dl
mov gs:[di+1281],al
mov es:[di+1281],al
mov al,gs:[di+1601]
xor al,dl
mov gs:[di+1601],al
mov es:[di+1601],al
mov al,gs:[di+1921]
xor al,dl
mov gs:[di+1921],al
mov es:[di+1921],al
mov al,gs:[di+2242]
xor al,dl
mov gs:[di+2242],al
mov es:[di+2242],al
ret
lblt_3b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
mov al,gs:[di+1281]
xor al,dl
mov gs:[di+1281],al
mov es:[di+1281],al
mov al,gs:[di+1602]
xor al,dl
mov gs:[di+1602],al
mov es:[di+1602],al
mov al,gs:[di+1922]
xor al,dl
mov gs:[di+1922],al
mov es:[di+1922],al
mov al,gs:[di+2243]
xor al,dl
mov gs:[di+2243],al
mov es:[di+2243],al
ret
lblt_4b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+320]
xor al,dl
mov gs:[di+320],al
mov es:[di+320],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+961]
xor al,dl
mov gs:[di+961],al
mov es:[di+961],al
mov al,gs:[di+1282]
xor al,dl
mov gs:[di+1282],al
mov es:[di+1282],al
mov al,gs:[di+1602]
xor al,dl
mov gs:[di+1602],al
mov es:[di+1602],al
mov al,gs:[di+1923]
xor al,dl
mov gs:[di+1923],al
mov es:[di+1923],al
mov al,gs:[di+2243]
xor al,dl
mov gs:[di+2243],al
mov es:[di+2243],al
ret
lblt_5b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+962]
xor al,dl
mov gs:[di+962],al
mov es:[di+962],al
mov al,gs:[di+1282]
xor al,dl
mov gs:[di+1282],al
mov es:[di+1282],al
mov al,gs:[di+1603]
xor al,dl
mov gs:[di+1603],al
mov es:[di+1603],al
mov al,gs:[di+1924]
xor al,dl
mov gs:[di+1924],al
mov es:[di+1924],al
mov al,gs:[di+2244]
xor al,dl
mov gs:[di+2244],al
mov es:[di+2244],al
ret
lblt_6b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+641]
xor al,dl
mov gs:[di+641],al
mov es:[di+641],al
mov al,gs:[di+962]
xor al,dl
mov gs:[di+962],al
mov es:[di+962],al
mov al,gs:[di+1283]
xor al,dl
mov gs:[di+1283],al
mov es:[di+1283],al
mov al,gs:[di+1604]
xor al,dl
mov gs:[di+1604],al
mov es:[di+1604],al
mov al,gs:[di+1924]
xor al,dl
mov gs:[di+1924],al
mov es:[di+1924],al
mov al,gs:[di+2245]
xor al,dl
mov gs:[di+2245],al
mov es:[di+2245],al
ret
lblt_7b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov al,gs:[di+963]
xor al,dl
mov gs:[di+963],al
mov es:[di+963],al
mov al,gs:[di+1283]
xor al,dl
mov gs:[di+1283],al
mov es:[di+1283],al
mov al,gs:[di+1604]
xor al,dl
mov gs:[di+1604],al
mov es:[di+1604],al
mov al,gs:[di+1925]
xor al,dl
mov gs:[di+1925],al
mov es:[di+1925],al
mov al,gs:[di+2246]
xor al,dl
mov gs:[di+2246],al
mov es:[di+2246],al
ret
lblt_8b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov al,gs:[di+963]
xor al,dl
mov gs:[di+963],al
mov es:[di+963],al
mov al,gs:[di+1284]
xor al,dl
mov gs:[di+1284],al
mov es:[di+1284],al
mov al,gs:[di+1605]
xor al,dl
mov gs:[di+1605],al
mov es:[di+1605],al
mov al,gs:[di+1926]
xor al,dl
mov gs:[di+1926],al
mov es:[di+1926],al
mov al,gs:[di+2247]
xor al,dl
mov gs:[di+2247],al
mov es:[di+2247],al
ret
lblt_9b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov al,gs:[di+642]
xor al,dl
mov gs:[di+642],al
mov es:[di+642],al
mov al,gs:[di+963]
xor al,dl
mov gs:[di+963],al
mov es:[di+963],al
mov ax,gs:[di+1284]
xor ax,dx
mov gs:[di+1284],ax
mov es:[di+1284],ax
mov al,gs:[di+1606]
xor al,dl
mov gs:[di+1606],al
mov es:[di+1606],al
mov al,gs:[di+1927]
xor al,dl
mov gs:[di+1927],al
mov es:[di+1927],al
mov al,gs:[di+2248]
xor al,dl
mov gs:[di+2248],al
mov es:[di+2248],al
ret
lblt_10b8:
mov al,gs:[di+0]
xor al,dl
mov gs:[di+0],al
mov es:[di+0],al
mov al,gs:[di+321]
xor al,dl
mov gs:[di+321],al
mov es:[di+321],al
mov ax,gs:[di+642]
xor ax,dx
mov gs:[di+642],ax
mov es:[di+642],ax
mov al,gs:[di+964]
xor al,dl
mov gs:[di+964],al
mov es:[di+964],al
mov al,gs:[di+1285]
xor al,dl
mov gs:[di+1285],al
mov es:[di+1285],al
mov al,gs:[di+1606]
xor al,dl
mov gs:[di+1606],al
mov es:[di+1606],al
mov ax,gs:[di+1927]
xor ax,dx
mov gs:[di+1927],ax
mov es:[di+1927],ax
mov al,gs:[di+2249]
xor al,dl
mov gs:[di+2249],al
mov es:[di+2249],al
ret
