extrn newdata1:word
;extrn newdata2:word

extrn background:word
extrn projxmul:dword
extrn projymul:dword
extrn projxadd:word
extrn projyadd:word
extrn projminz:dword
extrn projminzshr:word
extrn wminx:word
extrn wminy:word
extrn wmaxx:word
extrn wmaxy:word
extrn vram:word
extrn rowsadd:word
extrn truerowsadd:word
extrn truevram:word
extrn rows:word
extrn framerate10:word
extrn color:word
extrn color1:byte
extrn color2:byte
extrn video:dword
extrn borders:word

extrn xadd:dword
extrn yadd:dword
extrn zadd:dword

